pop0_site0_D:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAAAA8H8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.0001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        H2CNK8AUMb8DvQ0sOtMpP+ShfUWDQRI/lYfxEqpDEz8agdeFmbgmv8/gfLQ1iy2/9VmbZrs6SD/Q
        w3aFPqHtPj3QfdhR6w4/dqjQGP4UKT/AfvYD9DApv69E+iGaXBA/CAnprYxxNr8Vu744PGYnv196
        1q142j2/AteJ45zKK7+bBMecX4A3Pw==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        r3Zq/f//D0A=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: none
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 26001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        DgVF3wk0/j82qazileD6Pw5Qr1Ypp6I/W6Tu3McMKUCq+czqITUCQBIFqbCBz8Y/Yw4NXOihXD9P
        x2Eaef/UPwhr2cUEztQ/hXa6gwuExz9BZkrXvwS9Py6YF5qqlsQ/TXynEaEXyr+uSh3OpRjEP0r0
        rcGu1ME/8qlRYFFT1T+AEJx6QKjjPw==
    n_samples_seen_: 28
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        JZ+7eQW51z/Zkck+6cjcP1LmfmUtEoQ/In0u9YpTE0BvmmCV7cP/P17q+CfNjIw/UmEmIht9DT+5
        66WW/DaAPyPqCuCpnN8/eYZ9U1tmzD/BqB6FbrPPP8OQDydKcc0/2ojt8Jo2yz/YFTwcyanEP7wu
        RUE6Xs0/kRKX3A1p6T/3YfvuWwYGQA==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        /y1OpiWWwT+tsRWYheTJP8FqYiSGLRk/k/+0PB5YN0Dxo9vvS4gPQH6kNI7SeCk/Al73SaosKz5e
        Rtgltm4QP6Jc4x2IOs8/QY9UOWc0qT9TY9o/lGevPyfpK3vnFqs/oi5spIIkpz+Bgep4gK+aP0jo
        9gzf86o/l62pi34t5D9OxjZYf1EeQA==
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
pop0_site0_rg:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Ne45gZlmB0A=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAAvVoICdkTHPwAAAAAAAAAA+XLokRs80j8+KDQp1KPZvwAAAAAAAAAAbrjeU1Vh2r+5
        ZSqdGDbjv9/63IEQN7C/yDZdtD2wwb/iaRrG9yW2vzwxkhyYxr+/7H0j6ZMRxD9pKkQNZR+zvwAA
        AAAAAAAASmhJl1xl0z8=
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        eolXVFQND0A=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 26001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0, loss: huber, penalty: l1}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        DQVF3wk0/j82qazileD6Pw5Qr1Ypp6I/WqTu3McMKUCp+czqITUCQBMFqbCBz8Y/ZQ4NXOihXD9O
        x2Eaef/UPwhr2cUEztQ/gna6gwuExz9AZkrXvwS9Py6YF5qqlsQ/TXynEaEXyr+bjHX+9O0GQIBc
        fZktT/o/K1yJ03SXqz8=
    n_samples_seen_: 28
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        JZ+7eQW51z/Ykck+6cjcP1LmfmUtEoQ/I30u9YpTE0BwmmCV7cP/P17q+CfNjIw/UmEmIht9DT+5
        66WW/DaAPyHqCuCpnN8/eYZ9U1tmzD/BqB6FbrPPP8OQDydKcc0/2ojt8Jo2yz+iBoqYLeD/P7fQ
        Y5eX+dA/etTHj0yhoD8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        /y1OpiWWwT+rsRWYheTJP8BqYiSGLRk/lf+0PB5YN0Dzo9vvS4gPQH6kNI7SeCk/A173SaosKz5e
        Rtgltm4QP59c4x2IOs8/QI9UOWc0qT9TY9o/lGevPyfpK3vnFqs/oi5spIIkpz8T8SPWesAPQEPj
        q7JkArI/f5nLNfNIUT8=
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
