pop0_site0_r0:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    o1BPdX9N9UI=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        +vOG29Qo3z8u6ncsrEHQP80Aay6XD8E/RuQEpESrvz+bg15GSpa9v/KhA9+1bdU/FxdKDBUSKsCb
        VbhogsjKv5BZzSQuv3o/qDCufY2F1T8JvSTVAqzTPwd6BZGsBNU/29XgKbcT1r/KqyNG4RLYv9fB
        yJyTJbO/LyqIoDKh2L/PkNW5gt3Mvw==
    epsilon: 0.1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        RXcULM9WLkA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 13001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.1, l1_ratio: 0.5, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        6dTF8PUaLUBtYr0vYVzwPxGHSa5QRVI/0p9Xy/fxCEDR3e+h2WsFQD63wH0sCbo/NhrORMZPXD8u
        81E0cL+yP5GwZoEIzgjA77655MVt4b9GFUyWEBXav4mviczYI+C/AdydONu64j9ys/FEbxHEP1k0
        MQHJhYQ/YCiv/G1xxD/gw45GV0OIPw==
    n_samples_seen_: 14
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        TGFzvcRQBUDtJV8J6Ll4P/Kvhmk8vhk/rzakoKA24j8PpkWNL9vLP+6fTQxxUWY/lglUYCqCAj/k
        /bqonn18P/3mr2O/NxZAb5ywui6/pT9VfTDhePWiP4H8z+xE7aQ/KuhveH5mpj+JkOOrKlqTP5aE
        nHdj32Q/51uTE5zskz8vFR0nFeFoPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        gosoKpxlHEDxnI0XFBsDP2mfuVKptUQ+m2L666O71D/32omRvT+oP5XHkG2VId8+KqfKSQJpFT7f
        FuDJwl0JPwBz4o4Q2j5ANU1BFseOXT83xS4EBndWP3NzGNvqXls/sP2aW2xcXz8BBbx4IWg3PxfS
        F5KnOts+LvOxsJ3POD9HpC/szlfjPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal
pop0_site0_sigma:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    m6PFPzVp5UI=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        IYpmexnMM78AAAAAAAAAAKPf/JxrHio/AAAAAAAAAAAAAAAAAAAAAPvKvXodlkS/fOuISrfkjr8A
        AAAAAAAAAAAAAAAAAAAAwsK0k1/7M79FTpKl0v0zv9PFQATECDS/KRh2KVzoMz8AAAAAAAAAAOw4
        bPvZAU8/AAAAAAAAAAA5DMsQBNlgPw==
    epsilon: 0.001
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        W6Yp2kCqpT8=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 13001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.001, l1_ratio: 0.15, loss: squared_loss, penalty: elasticnet}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        6tTF8PUaLUBtYr0vYVzwPxGHSa5QRVI/059Xy/fxCEDS3e+h2WsFQD63wH0sCbo/NhrORMZPXD8u
        81E0cL+yP5GwZoEIzgjA7r655MVt4b9FFUyWEBXav4mviczYI+C/ANydONu64j9xs/FEbxHEP1k0
        MQHJhYQ/YSiv/G1xxD/gw45GV0OIPw==
    n_samples_seen_: 14
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        S2FzvcRQBUDuJV8J6Ll4P/Kvhmk8vhk/rzakoKA24j8QpkWNL9vLP++fTQxxUWY/lwlUYCqCAj/k
        /bqonn18P/3mr2O/NxZAb5ywui6/pT9VfTDhePWiP4D8z+xE7aQ/KehveH5mpj+KkOOrKlqTP5aE
        nHdj32Q/51uTE5zskz8wFR0nFeFoPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        gIsoKpxlHEDynI0XFBsDP2ifuVKptUQ+nWL666O71D/42omRvT+oP5bHkG2VId8+LafKSQJpFT7e
        FuDJwl0JPwBz4o4Q2j5AM01BFseOXT83xS4EBndWP3FzGNvqXls/r/2aW2xcXz8CBbx4IWg3PxfS
        F5KnOts+LfOxsJ3POD9IpC/szlfjPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal
