accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  oYEkyKI65T8=
model:
  C: 1.0
  _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [8]
    - *id001
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
      AAAAAADwPw==
  _max_iter: 10
  _tol: null
  alpha: 1.0e-05
  average: false
  class_weight: null
  classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [8]
    - !!python/object/apply:numpy.dtype
      args: [U98, 0, 1]
      state: !!python/tuple [3, <, null, null, null, 392, 4, 8]
    - false
    - !!binary |
      cAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8AAABz
      AAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkAAABuAAAAaQAAAGUAAAByAAAAXwAAAHAA
      AABvAAAAcgAAAG8AAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAA
      AHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAA
      dAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAABy
      AAAAbwAAAGQAAABfAAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUA
      AABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAAAABoAAAAZQAA
      AHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAAcgAAAG0AAABhAAAAbAAAAF8AAABfAAAA
      cAAAAG8AAABwAAAAMgAAAF8AAABmAAAAYwAAAGMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAw
      AAAAXwAAAHMAAABwAAAAaAAAAGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAHAAAABvAAAAcAAAADAA
      AABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAA
      ADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAA
      cgAAAG0AAABhAAAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAABk
      AAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8A
      AABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAA
      AGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAxAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1AAAA
      cwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4AAABp
      AAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAA
      ZgAAAGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABw
      AAAAaAAAAGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwA
      AABfAAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAA
      AF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAA
      cgAAAF8AAABwAAAAbwAAAHIAAABvAAAAZAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMgAAAF8AAABm
      AAAAYwAAAGMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAAAGUA
      AAByAAAAaQAAAGMAAABhAAAAbAAAAHAAAABvAAAAcAAAADAAAABfAAAAZAAAAGkAAABmAAAAZgAA
      AHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAAAABoAAAA
      ZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAAcgAAAG0AAABhAAAAbAAAAF8AAABf
      AAAAcAAAAG8AAABwAAAAMQAAAF8AAABoAAAAYQAAAHIAAABkAAAAXwAAAHMAAABwAAAAaAAAAGUA
      AAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAA
      AG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAABoAAAAYQAAAHIAAABkAAAAXwAAAHMA
      AABwAAAAaAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAA
      AGcAAAB1AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAHUAAABuAAAAaQAAAGQAAABlAAAAbgAAAHQAAABp
      AAAAZgAAAGkAAABlAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AA==
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [8, 13]
    - *id001
    - false
    - !!binary |
      p5RKkqDoVEBp5npiXupBwOZXW/P3F/G/o1VfaxD7HsCobiOCcu84QFpuH361R1BANMeNzMkMTcCs
      D08jSlJBQIWqIdvWEVfA3YjIBbLRVcBdB6rUiKs6QEvMNEUx/0nA9yMgSfRmXkBSSy2LrWhbQPux
      0WFWsWXAuRYyC5sOOcATjQxPmuhwQHw0z9RnEjBAmOdz3I0BTsDA9UyCtdNlwEv4JZ7KtlDAWxv1
      aLVTYsAH5olNYaoJQNmzn4q1ICRA/uDRlEecFUBU/v6NoUrwv0yegKFMyTjAOzcboggGBEBEYXcd
      o+8bwJWLl0Miuj7Akxs0yN5oNsBfXdQUChNiwGUgzKJws1nALbNIEFShW8Bcxk9c1EtJQImn9wkg
      7yzAAnYmbp+PEcBHHJRrgAInwJR3elOGZjFA7MvteQX2KcAQreLBXfpCwHjjdhVvrFBAVZ3TvT66
      QcAj2elL2dVAQLqk52pXl0bABHiM4lEqQMDsn9rpn3tBwHOniz2DPzHAAqbx9+ODMMBdtXLS105B
      QPt5AJr77+S/GzazJDVpQEB6zv1e4JFfwEPyJtUQY21AtNINYOHjTMAK7a81r6FrwKdYFxdikExA
      1DdE8s/9GkCKz0pJZvNOwJDZ2n7CPVzAgMxLw/nGSMAol9eNXQA3wEVR6kWrax9AyKc3XWSSKsDT
      9IwsWkxAQBWUGsM3yDBA03HtsP5yUcBJk+BnzHBrwCZzrGjDZ1nAmQ47+Eg1IkBhofHsjNxjQIZK
      Oe0itDBARXj4AQ+xB8Ad6c1wOYFiwBby5EOunkPAAPsLOvikXUAxB973bjUiQHqP/dizCVZAORbc
      cdImUcDqjZONBs41wNdlJ9RHAgHAOgGizX/KS8AiuagZjygkQE7pi2qe5wlArrSYrOloUECnijLO
      HzRHQCrWOQ8jcFRAtAPas+cNM0BT4UDGvtIywKQNw9MdrBNAcKzJhZiwPMDL4QpTdH9cwGS973cp
      wvQ/5WaB2eQ0UMAs1jYLJ6BGwB2rzcERETFAR1W/MMoMYMDxSW6labkrQNgoFZB8XVVAAj8gbfkI
      VcC8ltnxcdU1QJ3B76iMe1TAyd39nGi4IMD6yOLZ/cdLwA==
  epsilon: 0.1
  eta0: 0.0
  fit_intercept: true
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [8]
    - *id001
    - false
    - !!binary |
      847q2fhVa8Azb/FCLptkwLqUJH3XtXDAsDE0yyL1WcCMUccWvZprwLks5vKVrmbAlwAY5NrXX8B7
      0PVCeaZpwA==
  l1_ratio: 0.85
  learning_rate: optimal
  loss: log
  loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
  max_iter: 10
  n_iter: null
  n_iter_: 10
  n_jobs: 1
  penalty: l1
  power_t: 0.5
  random_state: null
  shuffle: true
  t_: 3601.0
  tol: null
  verbose: 0
  warm_start: false
parameters: {alpha: 1.0e-05, l1_ratio: 0.85, penalty: l1}
scaler:
  copy: true
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      5aHpxgfrKkCi1rP/xL/1P5hgmIzGf30/aoOTMh5kO0CYvjXHhV0JQC94w+vMDb4/7C8supIHZT/5
      XZkDY4TEP+wJvPrGIcU/8b5bk6/S5L80qhpNL03iv0bD8lUlJOS/JwQHHtB05T8=
  n_samples_seen_: 410
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      2weW7adVMkCdMOXYgDnmP3VLst/sEoA/cLPytS4iS0CR1C3KiVDrP9d6NITSRJU/GwDCco07UD8w
      5YLj4JW0P+pAhoU94+U/ij/QvznhzT/Yge0MrJXMP3W+9FIbTM0/IO9a9iKMzj8=
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      JGmwZYQCdUB6QI3+8N7eP1a7DiLwJRA/rmGQVtMBp0ACjHE4s1DnPy5TP6PQRTw/ytCUjfh3sD7Y
      ka0xLnx6P1G6GeEc8d0/fAsr4Gnmqz8CEnUkqYipP5D4PIim0qo/8k78PycprT8=
  with_mean: true
  with_std: true
