cross_valid_results: null
model:
  C: 1.0
  _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id001 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [6]
    - &id002 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/
  _max_iter: 10
  _tol: null
  alpha: 0.0001
  average: 0
  class_weight: null
  classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [6]
    - !!python/object/apply:numpy.dtype
      args: [U46, 0, 1]
      state: !!python/tuple [3, <, null, null, null, 184, 4, 8]
    - false
    - !!binary |
      cAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8AAABw
      AAAAbwAAAHAAAAAxAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHAA
      AABvAAAAcAAAADIAAABfAAAAYwAAAHIAAAB5AAAAcwAAAHQAAABhAAAAbAAAAGwAAABpAAAAbgAA
      AGUAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAA
      ZQAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABl
      AAAAXwAAAF8AAABwAAAAbwAAAHAAAAAyAAAAXwAAAGQAAABpAAAAcwAAAG8AAAByAAAAZAAAAGUA
      AAByAAAAZQAAAGQAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAA
      AGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABzAAAA
      bwAAAHIAAABkAAAAZQAAAHIAAABlAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAG8AAABwAAAAMAAAAF8A
      AABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAxAAAAXwAA
      AGQAAABpAAAAcwAAAG8AAAByAAAAZAAAAGUAAAByAAAAZQAAAGQAAABfAAAAXwAAAHAAAABvAAAA
      cAAAADIAAABfAAAAZAAAAGkAAABzAAAAbwAAAHIAAABkAAAAZQAAAHIAAABlAAAAZAAAAHAAAABv
      AAAAcAAAADAAAABfAAAAZAAAAGkAAABzAAAAbwAAAHIAAABkAAAAZQAAAHIAAABlAAAAZAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAB1AAAAbgAAAGkAAABkAAAAZQAAAG4AAAB0AAAAaQAAAGYAAABpAAAAZQAAAGQAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAA
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [6, 22]
    - *id002
    - false
    - !!binary |
      boLEYUK/R0Cyx5QqfN44wMS8wBAouThAovYvsfiAMsAuwvzkZOM+QHlwsGv35jvADxxyWMevNEBJ
      7HdtZkAgwIYPqgdh6DbAIHgyvZMXI8D1a7H5ciMKwPyjL4/UMfM/2xPUzBTi/78wWIE9vH8RQANB
      erIDpO4/PMwXLpNuBEC75Q1jTa05wMKh8gOmFUDApV7BjeIgM8AUQpBpkVAiQLw3UvjoTjJANhXo
      oJmUJMCqMmpFhfP9P24u/5W2VClAGjy20ZbtLMAsKkanjBMRwPH4qABjbybA7U4k3dMCJsBF+W7v
      feYSQBLKANEmSivApeWIjbtbJsCaonERoI83wGAlMezcQBjAbccuFSuSFsAD8nFue04YwPp54Vk2
      aRhAEX6Xmpq5EUAQSCWrhgZDQF9K3Uy+zTrARWFahnuG4z/TkcQEDFMYQGIlgQXl9yrA07QyIgek
      KMALfl/2oR5DwGtrGVOppTPAibirX7zZK8AHeVf/tLX8v8KYB9UuZCXA137fPSFmDcDnRdlf5DEU
      QAEADW0byyjAyKYo/aLVHUDW7p/9CdE7QGlkNS1/ECrALWnN5rdNQ8Dbi+awssAuQOj+5MK22TfA
      x0vQMzhRSkA03e4AeO84wPMr+v4ySyNAiXOzzVYpCcAJf7/q4JczwH87eLFeSShARqkmOetVQUBM
      DKsnb0QGwE0adEnI6y/AKzD66R3FPsCeTzxYjFTyP+Z+LEms8fw/1pqIJGBsNMCST06aTR82wGVX
      XJq1wB3A0WF+cgfeTMBKrn2AMskUQF458/uwLQxATJnzW2uyKsDxYvKSpysywKMjprE/fRbAIocr
      SxypLcDohFgjujQ1QET/3O0FgAxAk9niQUgOMsDYYilEDZMwwD7mbMU1oiLAHspvD+URIMCnSJL0
      7EsoQOc2roFklUXA87iOzef+2b97imjOsFkEQNkOVgmqn7M/D6flqA/ZIMCsxgNhW1pLQLl1wM7Z
      L/M/0wdKrwK+GUB4jdZ9LalHQHbt2UwP3TDAFnpcrj2VE0DkiD2By2A0wJXIUzL5UfM/Djeo6+Co
      N8Aclxyaeo4XwNQAqI2vzB/AvnbJswd9+7+LQSVGH8gTQAZfShZc+jjAynUw8ULmFUCv0kh4Hpcy
      QC/GSxku0Oa/SYQ819a1MsAfMqLBCmElwHgxTQaEaUvAHoJHpM/wMEDH2T3C24ggwJ8b3ydyTkrA
      h+Gqc+TjRMCzqKH7X6k8QHn46yOZuh5AaVzgNfYRG8AodUhDvXBCwE6uOiDheRBAC/QovcclN0Bm
      JLnbGxQfwDLyq5z40S1Az+eZIvtZP8CmawHWJgwjQBVFrT9JMjjA6h6a7UxzM0BP5T2SN9UzQBGX
      kax/NEVAcuhd0VfPMsCscoHfX5YwwE6nYToMbTJA
  epsilon: 0.1
  eta0: 0.0
  fit_intercept: 1
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [6]
    - *id002
    - false
    - !!binary |
      VaHGeXR1XMBpBeoFeEVnwPXwyiYKuWPAzTI0kmhXYMC0Zg3tTRJhwMe1uCQ3ABvA
  l1_ratio: 0.15
  learning_rate: optimal
  loss: log
  loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
  max_iter: 10
  n_iter: null
  n_iter_: 10
  n_jobs: 1
  penalty: l2
  power_t: 0.5
  random_state: null
  shuffle: 1
  t_: 2111.0
  tol: null
  verbose: 0
  warm_start: 0
scaler:
  copy: 1
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [22]
    - *id002
    - false
    - !!binary |
      KocTt9iwLkBc65B1RCUKQHjXc+p3M/Y/WSFo9pZUB0BkaLb/nlsRQDLlo0bjMRxAIxMtds1/uj+N
      eqUP6sBeP5o5HkL6b8o/wRqZglmTuj/7XZ1h+h/av+o5kAHXy9q/6l2Arax92r/PXUUoiJnZP21+
      hjT6Sro/uh9GBYxutz8vJ16OCTaLP6zoEN24UdQ/0kDZIB8uuD87w+NJy1q4P4Ktn54bDIk/PrsR
      Xt6pij8=
  n_samples_seen_: 211
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [22]
    - *id002
    - false
    - !!binary |
      K9SLKTXTMUBYsmcSDtAIQJPNdkGxvdk/uky9jn9qBkAstlUSQgUCQNd8qPfv+hBA4JbScERhoz8L
      ZAPuiPQ4P2lPV85SV7o/kgRyfW954z8B6oqxSnPUP/cSJmIp/dE/cHiI5heH0z9oUQuxxHDVP0cH
      b2hc/ss/uTM6P3lIxT8RY9I/51KyP906VIKVEARAttTxgLiPzj8nuVF75zrKP3P1TT74SbU/GCS+
      1/2KtD8=
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [22]
    - *id002
    - false
    - !!binary |
      gY4hA7Xbc0C4/5DSXT0jQErJ9G/JtMQ/L86kpqNnH0DOJp1j1ksUQK9QW4g/BTJA1OHw2lF5Vz/N
      t3wPGnaDPnwiZtrUroU/xQdBcwK01z/eJ/B+eSO6P8Llu52dObQ/vRD6Zk3Vtz9hTd4bH7u8P68Y
      QMwhfag/4qDIjIZPnD83z/XeNfx0PyRLTPaGKRlAF63tbv8vrT9lUw6WJIClPxG40JuBU3w/ZSzg
      BTJgej8=
  with_mean: 1
  with_std: 1
