system_class:
  cross_valid_results: !!python/object/apply:collections.OrderedDict
  - - - 'all system classes :'
      - [unidentified, pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical,
        pop0_hard_spheres__site0_guinier_porod, pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod,
        pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_hard_spheres__site0_spherical_normal,
        pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod__pop2_hard_spheres__site0_spherical_normal]
    - - 'confusion matrix :'
      - !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - &id001 !!python/name:numpy.ndarray ''
        - !!python/tuple [0]
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple [4, 4]
        - !!python/object/apply:numpy.dtype
          args: [i8, 0, 1]
          state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
        - false
        - !!binary |
          OwAAAAAAAAAKAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAcAAAAAAAAAGgAAAAAAAAAA
          AAAAAAAAAAMAAAAAAAAAAgAAAAAAAAAKAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAMA
          AAAAAAAAAQAAAAAAAAA=
    - - 'model was NOT tested for :'
      - [pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical,
        pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_hard_spheres__site0_spherical_normal]
    - - 'model was tested for :'
      - [unidentified, pop0_hard_spheres__site0_guinier_porod, pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod,
        pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod__pop2_hard_spheres__site0_spherical_normal]
    - - F1 score by sys_classes
      - !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - *id001
        - !!python/tuple [0]
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple [4]
        - &id002 !!python/object/apply:numpy.dtype
          args: [f8, 0, 1]
          state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
        - false
        - !!binary |
          CrqrFBN05z97Ce0ltJfQP0xnMZ3FdNY/AAAAAAAA0D8=
    - - 'F1 score averaged not weighted :'
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          N3kd+yd92T8=
    - - 'mean not weighted accuracies by system classes :'
      - pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical: []
        pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_hard_spheres__site0_spherical_normal: []
        pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          JUmSJEmS5D8=
        pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod__pop2_hard_spheres__site0_spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAAAA4D8=
        pop0_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          VVVVVVVV2j8=
        unidentified: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          PcWyj0fw5j8=
    - - 'mean not weighted accuracies by exp :'
      - R2:
          average for exp: !!python/object/apply:numpy.core.multiarray.scalar
          - *id002
          - !!binary |
            N93499YR1D8=
          by classes:
            pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              27Zt27Zt2z8=
            pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod__pop2_hard_spheres__site0_spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              AAAAAAAAAAA=
            unidentified: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              ZHA+Budj4D8=
        R3:
          average for exp: !!python/object/apply:numpy.core.multiarray.scalar
          - *id002
          - !!binary |
            Ks2LP5Fw5j8=
          by classes:
            pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              AAAAAAAA4D8=
            pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod__pop2_hard_spheres__site0_spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              AAAAAAAA8D8=
            pop0_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              VVVVVVVV5T8=
            unidentified: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              Ut/ZqO9s5D8=
        R7:
          average for exp: !!python/object/apply:numpy.core.multiarray.scalar
          - *id002
          - !!binary |
            AAAAAAAA5z8=
          by classes:
            pop0_diffuse__site0_spherical_normal__pop1_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              AAAAAAAA8D8=
            pop0_hard_spheres__site0_guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              AAAAAAAAxD8=
            unidentified: !!python/object/apply:numpy.core.multiarray.scalar
            - *id002
            - !!binary |
              AAAAAAAA8D8=
    - - 'mean not weighted accuracy :'
      - !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          Q+67104r4j8=
  model:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [4]
      - *id002
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8=
    _max_iter: 10
    _tol: null
    alpha: 0.01
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [4]
      - !!python/object/apply:numpy.dtype
        args: [U119, 0, 1]
        state: !!python/tuple [3, <, null, null, null, 476, 4, 8]
      - false
      - !!binary |
        cAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8AAABz
        AAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAAAGwA
        AABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAxAAAAXwAA
        AGgAAABhAAAAcgAAAGQAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABlAAAAcwAAAF8AAABfAAAA
        cwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8AAABw
        AAAAbwAAAHIAAABvAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1
        AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAAAGUA
        AAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABfAAAAXwAA
        AHAAAABvAAAAcAAAADEAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgAAABlAAAA
        cgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkAAABu
        AAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAXwAAAF8AAABwAAAAbwAAAHAA
        AAAyAAAAXwAAAGgAAABhAAAAcgAAAGQAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABlAAAAcwAA
        AF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAA
        YwAAAGEAAABsAAAAXwAAAG4AAABvAAAAcgAAAG0AAABhAAAAbAAAAHAAAABvAAAAcAAAADAAAABf
        AAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGUAAABzAAAAXwAAAF8A
        AABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkAAABuAAAAaQAAAGUAAAByAAAAXwAA
        AHAAAABvAAAAcgAAAG8AAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAdQAAAG4AAABpAAAAZAAAAGUAAABuAAAAdAAAAGkAAABmAAAAaQAAAGUAAABkAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [4, 22]
      - *id002
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJsboAjOFA0CcGxe5J4n7PwAAAAAAAAAAztBwtLIu5j8c
        xQAg0GjuPwAAAAAAAAAAAAAAAAAAAAASaAJp67sOwAAAAAAAAAAAbRZnAMGPBsBm0fS8mCYTQBrj
        Yj5hqxLAc0EcyQfp6D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0S/xa2Df/PwAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCqZYHUj87/CkkrW
        E4AUwAAAAAAAAAAAVi27aB7O8r9zgqTKgZHHv81oytmiJQnAspAQZ1pJ2r8keN8J22UDwLjrnwG+
        7Q1AFir8wtuf9z/Zebw4Na/1v284nFMPcifAAAAAAAAAAAD00p7Ep9i7vwAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8HR3Zid/U/xiRI9Ga7EEAAAAAAAAAA
        APZS5a3moRFAdN5mtGgiEMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAOtvWqj2KCUDwKBocmPD7PwAAAAAAAAAAbp1/Hr9K1b/Qmb/9c3EWwAAA
        AAAAAAAAvrmpzrdu6D9N0BFMwFnXvwAAAAAAAAAAkJO8pJyW8j+IYD/JnCXoPwAAAAAAAAAAAAAA
        AAAAAADuFHkHA+7/v1uZ/mqbFP0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wf5R
        3hUNwAAAAAAAAAAACeOTbucBBkA=
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [4]
      - *id002
      - false
      - !!binary |
        9yh9otVOJcBXQXmGTEUvwFtQfXg8YSrAJXgztAt4BEA=
    l1_ratio: 0
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: 10
    n_iter: null
    n_iter_: 10
    n_jobs: 1
    penalty: l1
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 1071.0
    tol: null
    verbose: 0
    warm_start: false
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id002
      - false
      - !!binary |
        qGKhJP7aJ0DzSitLF9cEQK6OjTHUi/U/JhZ9Xl1OCkCQtbXZ8YURQM4TErA1Dx5ALG7oIxSXuz8y
        SkSlqgxfP7mb+agikcw/RdRoJzSrwz/Xb+gDlTvbv3mT531Eady/W78/Q8LC27+fZLpcH4faP587
        7DQ1Ib0/GsomcJJzuj9OZhm1UGaQP10dC4QQoNg/1LISCYq+uj+K4+F84HC7P7OCIY/HY40/5OmN
        ozgQjz8=
    n_samples_seen_: 174
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id002
      - false
      - !!binary |
        H5xOO6pjL0BocW7z1iUFQN/iNkaaztk/bMYToi52BkBpws+KNzwDQI3hhXOObRFAgKjz88uXoz9S
        uALLv1U7P61NkjnJhLg/lBHoXfKL5D94gc4UGozVP+Y8IqrO2dI/GknE80SU1D8j90PWCpDWPxKk
        Kxbooc4/jxWACQgoxz8rBHbA8Ru0PxewFhLVDgZAlv3oHqHA0D+yhIMxv6XMP1WXHpwoaLc/NAtC
        WkOVtj8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id001
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id002
      - false
      - !!binary |
        dNvAO1DKbkC/hm+8rfMbQI+J5fIG0MQ/s+8ULmmIH0D0Uv+K5h8XQDjFVt+8+zJADBQnhyT+Vz/2
        mfhtmVmHPirHZ9dUyYI/9yY7/KVi2j9utTQ/jwS9P7xNAf+lNbY/kIwxXgp4uj8MBlOQLtG/P00s
        hFfGUq0/9+PBob3BoD+pV1UvDUZ5P6N9s7HXaB5AP1EOX1GKsT/eG8sWaaWpP6hJlmgNH4E/xzLC
        r+nffz8=
    with_mean: true
    with_std: true
