system_class:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    56E+PkJA4j8=
  model:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - *id001
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 10
    _tol: null
    alpha: 0.001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - !!python/object/apply:numpy.dtype
        args: [U119, 0, 1]
        state: !!python/tuple [3, <, null, null, null, 476, 4, 8]
      - false
      - !!binary |
        TgAAAG8AAABpAAAAcwAAAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1
        AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4A
        AABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAAAABf
        AAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAA
        AABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8AAABwAAAAbwAAAHIAAABvAAAAZAAA
        AF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAA
        XwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABj
        AAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAA
        AAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAA
        AHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8A
        AABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAA
        AGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYA
        AAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAA
        AGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABfAAAA
        XwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABf
        AAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8A
        AABwAAAAbwAAAHIAAABvAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAA
        AABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAA
        ADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAA
        cgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABm
        AAAAdQAAAHMAAABlAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkA
        AABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAXwAAAF8AAABwAAAAbwAA
        AHAAAAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAA
        cwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAA
        AF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAA
        YQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAx
        AAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAA
        AABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAA
        AGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABf
        AAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgA
        AABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAA
        AGkAAABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAA
        ADAAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAA
        ZQAAADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABv
        AAAAcgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABoAAAAYQAAAHIA
        AABkAAAAXwAAAHMAAABwAAAAaAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAA
        AGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAA
        bwAAAGQAAABfAAAAXwAAAHAAAABvAAAAcAAAADIAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABz
        AAAAcAAAAGgAAABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8A
        AABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAA
        AGEAAABsAAAAcAAAAG8AAABwAAAAMAAAAF8AAABoAAAAYQAAAHIAAABkAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1
        AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAHUAAABuAAAA
        aQAAAGQAAABlAAAAbgAAAHQAAABpAAAAZgAAAGkAAABlAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11, 13]
      - *id001
      - false
      - !!binary |
        OVD7ps48A8BMDuV6PYLJP6T/VR8Qke0/OHn3d5GYp7/wBrFRu2jxP1aooVVsJgvAHFiqVAIU5b+5
        T27+NE+xvz5SdraMcuO/99OMtIKo8D9uHZD6//zyv+rHxMXY0N0/bX8n9FR6+79pDqser3oJwLES
        aqD+8xXAQ3drKlz2kT+dO32OtJsIwFqIuRrcE+A/2/zN6jZUHEBvVDarpdnmv4NskCeEDA5AFXa3
        AEDfu7+3v9BqwP0SwFCvKSNpaBTA3/qOlDiCE8BsOJeZSYoSQFw5hbkv6BlAJfo5G1UUB0AeBhiZ
        WPcMwDe2htwp1hJAiECQmUm87D/E91FW5nD0v0ms2GNmkp4/dLLHeu6PFcBDKwcTj+LAP4P/HRlr
        1/K/Q67HfJKp3b/hXb5SMifvv7sZS0qB5vU/DjEk+6j81j8LbQzNd+4TwCdu3tHEyxPACZaCjAzK
        C8CQEQaeZU/tv5L6YWG64vS/nuHXNWCmAsC27buRm80bwBSfn5XWYpw/WDNuNccA9b8fliT5mlTR
        v4CYYZqhVfC/+3uOZqyg+T8x6l1j5FfwvzYpO80HXRTAZwnBx6mDBsDlj5aZPj/4v1mzeQNgrM6/
        To/JU8rg/b/aA2q6MrX2P5tW2SFZeBbAiSurUvkX0D+vvzZprYMLwLCFuHASQgLAPRjrHSrvCMA+
        WoIocvMNQM2gr6A2txJAEiBr43iTA0DYcyr0TGkPwDe/9qt/qPu/nQfwHjVx4D9g5kK2tN0EwG7x
        Uhp2DAFAxAGMHVVYIMA8IERfPByjPwvhtE8MnPy/YwCxQxT94L8xqKkRdNT2v0Z/H5SiAAFA8vSS
        8qKRAkBu3giNJ0DzPx9VOwiWAhbAaf1VhQ72/L/VXqU+vrbjvx/8/NqEMvi/zjWndc6yE8BG7QcF
        loQbwEfHD5omMMA/x3SfHZvB/L/kJrUYxNHbvxZb8OtSfva/F3QKUIFNAUCxPR670DwWwGRa2XP5
        XgTAti+uvPBs+j8M0R6ljxABwAnP1V+WtOO/g+lMuvLn07/miAs7hxeDv/UWza8JVArApa37iHmz
        vr86uaYZ5AT/v0VCyXOTXQxAGFyMG++J178nJGgkBq0LQOzMGCTt9f6//meZylSJCcABDu0HOaAR
        wFwVS2uzzgbAG6MxCYUZ8b+A6V4R1cogwEtT7ybwrce/0ZdCV/a0DMAJAA98UqDSP0Iyiwo5XxDA
        Pcab5cG1CcBFBU4IG8wOwIpqVceXPhFA2PpWgvigA8BXxIxQnCnrv/Hw4zOi+rA/N9Pn9IXX879r
        xYZOaL3cv7Iq6CdKlgZAvU0qL5q87z+ebS3eSzUaQKxgJx9sf8s/0YlhM1mm3r9j2gEpYmn2v19H
        GvZMYuu/KCsIB2Sv1D/evntGObAIwC4i2pYLFgLA8t4LCPkLwr/flrXjlJXgvzRZHRVIqP8/V+mw
        /K25+T+7iUeoBG/ePyfW3xCLEABA1LeD/CrJuz9sFZy2c1oOwMzxalzwOxPAF+1vShplEMBruWBT
        f+sLQA==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - *id001
      - false
      - !!binary |
        wyH8gE331r9p8vQkJIJAwPNT5We5/ETA6PO/eBU/N8AQnGGfylM4wNKwspKQBTrA1KVHFtN7NsCi
        LCHEAoQgwDte8172sj/AwVWbrgO8JsDdrvzuhKA7wA==
    l1_ratio: 0.15
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: 10
    n_iter: null
    n_iter_: 10
    n_jobs: 1
    penalty: l2
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 5741.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.001, l1_ratio: 0.15, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        wHHy+LMBK0BYIChJhKL4P1mj/2d/sok/kml09bX+NED8aUQaqa0IQDhktj4qoL4/PYBhI2bhYT8C
        4KUITqnKPyr2ooOSOcA/rGFd/nYd1b+CJG/myyjUv5zQnd9K9NS/rUGVENU91T8=
    n_samples_seen_: 599
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        i2OJfQb1MECBdwMmiXrpP2kKeYPBOok/I1vaDltGREDJoQKS0xP3P7bPVnjeGKI/e4QbTu7dTj+4
        42OVpUa6P4uNEBvTxxNAUr9z6kWs3z/5zsRfmH3bP7z3ecGHZ94/0DNrKU904D8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        nvjZUbX4cUDTEnODS0nkPwrzez865CM/dhPqAxmxmUDO+5dqjKQAQLumQTYbeFQ/FB/5/CHGrT5f
        togKaZOFP+7laf5UdDhAwWBx5mZZzz/C3d0S3p3HP7Me8n5t48w/fqM20Ovr0D8=
    with_mean: true
    with_std: true
