system_class:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    15RS1b5w4j8=
  model:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - *id001
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 10
    _tol: null
    alpha: 0.01
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - !!python/object/apply:numpy.dtype
        args: [U119, 0, 1]
        state: !!python/tuple [3, <, null, null, null, 476, 4, 8]
      - false
      - !!binary |
        TgAAAG8AAABpAAAAcwAAAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1
        AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4A
        AABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAAAABf
        AAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAA
        AABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8AAABwAAAAbwAAAHIAAABvAAAAZAAA
        AF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAA
        XwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABj
        AAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAA
        AAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAA
        AHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8A
        AABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAA
        AGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYA
        AAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAA
        AGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABfAAAA
        XwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABf
        AAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8A
        AABwAAAAbwAAAHIAAABvAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAA
        AABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAA
        ADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAA
        cgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABm
        AAAAdQAAAHMAAABlAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkA
        AABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAXwAAAF8AAABwAAAAbwAA
        AHAAAAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAA
        cwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAA
        AF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAA
        YQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAx
        AAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAA
        AABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAA
        AGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABf
        AAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgA
        AABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAA
        AGkAAABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAA
        ADAAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAA
        ZQAAADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABv
        AAAAcgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABoAAAAYQAAAHIA
        AABkAAAAXwAAAHMAAABwAAAAaAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAA
        AGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAA
        bwAAAGQAAABfAAAAXwAAAHAAAABvAAAAcAAAADIAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABz
        AAAAcAAAAGgAAABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8A
        AABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAA
        AGEAAABsAAAAcAAAAG8AAABwAAAAMAAAAF8AAABoAAAAYQAAAHIAAABkAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1
        AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAHUAAABuAAAA
        aQAAAGQAAABlAAAAbgAAAHQAAABpAAAAZgAAAGkAAABlAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11, 13]
      - *id001
      - false
      - !!binary |
        L4LbT21O6L86Y1CgI+HJP6sM4awXgdc/ak0n8//1pr/1iMIhrSrgP26UxJ1Tdvq/PxVYwop55r9y
        RngB+c/bP/PF8rtq2qa/ebTnDTp+2z969Nez89qFv3waDyw6s9M/A5EQQXy+4b+cYwl5GKngvxzk
        jEALM+e/nIXtvsuGyL+KIxz36Q/Xv8OGFUPF7tU/XLcP5dsu9j+M4JGF3FKwP67C/vUsK90/uVe1
        +JIYmD+uS+PWvq3yv/zxIKQagPS/VKREA1ZG87+AWu8x2xTyP5B4gI7qB/M/PS48Ie0x4T8Y0ut2
        ShjXv9akDPMxofI/kOExPmCywT+OxcJs0yutv24CzM5u9dA/X8ihAM/F4r/HjTLMaJiHP0OEHKZX
        YKm/TN3iKAWqlT/CZzkjv4Cdv/8daHvOlbE/wgBRvpDwsb/VQSmuA4nxv5g1UKche/O/ABzTxCkP
        5r+OpEIyV3DXv6D+80cHS9W/0dNq7HeH5L9HAXwFKPD7v8sTG8vWLMC/EHaJdoxn3b/DaHW6gPLF
        vw1qtlxRNti/2yaMsQI74T+zgZ0+ELHSv+Qb4fIOq+S/uPFKoiW45r9kjoqEVmjXv3WH4uyrv8K/
        X2kr4Qar17/vZM8G3LHSP7TovKe6g/C/xsg0WiUOnT/GEjyRaf7kv9x2LORg/dy/iVpKBSIs478F
        K5VCTLLmP3FDCCZ1ofc/scyjmDWh7D8VVt3fMMfjv4uDr2Xa2di/q8qvsX7msz+Y9gFO1t7Yv/Jg
        1bW5beA/9RcxtN5K8r8CqQGVdmORv+ak7crR0rW/6/PaqHcurD9xxUiIHpOmv0EccKdfkb8/FaCr
        H0iH3D8oR+m6cCzjP7Ce3/xOu+m/O9w5T7Nt679Ty9ActJTRv7p+1yY4KuC/wukKekLO77/Vjztc
        iaLyv+dhGxmTEMC/zJdC74tZx78upLGv+VWWP8m9mNu1qL+/UPa+zjOAzj8mv3Yy/E/xv9OVgVmH
        pea/yYHT10CHoL8h/iwn5O3Yv+FObl7qFvK/3CdCWPb23b8dVyJ8R9GTPyfkAXhcZuy/d8CX1/zI
        fj+3b0IuNQDfv1vQDAk1vtI/YfkyAcau0L8SZjAvwVnmP3r2uFwyg8C/l3zj9VmXyr9otRJl5rjj
        vw5Mt9YVqNW/NlxhoJXjyL++2HLDQ73vv4+keg/JWb4/7jifLWac4L+Ez7ppmbnYP1MwzzzxBd6/
        mvG6L7Yo1r9GUafcytDbvzQSmMBuA+A/O3ah1QEJ4L9kIUvyHXzGv1fPrFt4IdU/8gKguF2c2L8t
        a3KK+A+jvzawysUcVfQ/tSoSxdU26D9CG517vZfzP6hhmfYxJbI/2CzkUefXu78XvbflGUjYvzl6
        XkSfVMm/huj1Re3KpT/xvDT5bl3bv44KroLNydO/9r59lGUbs79bQbUC6EOyv08jX8z+O8s/h+oe
        DPe8zD8rXPslHo/DP0K/4242pcU/LTI45TaGbT9s6WtS2g7lv4NdUI3IWOm/oRd63WlZ5r8D6ith
        L7vjPw==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - *id001
      - false
      - !!binary |
        aDiZFdpey7/5p5IMC2IdwNdQcZ8lcx7AlT4M7iBgHcBtzY8nAo8ewACojI8zLh3AH3MFAzhEFcCc
        1mgA+MoOwBg5DnbemCTAr2V2blX+EMDKj/7aXoQgwA==
    l1_ratio: 0.5
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: 10
    n_iter: null
    n_iter_: 10
    n_jobs: 1
    penalty: l2
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 5611.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, l1_ratio: 0.5, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        wHHy+LMBK0BYIChJhKL4P1qj/2d/sok/kWl09bX+NED9aUQaqa0IQDdktj4qoL4/PYBhI2bhYT8C
        4KUITqnKPyn2ooOSOcA/q2Fd/nYd1b+CJG/myyjUv5zQnd9K9NS/rUGVENU91T8=
    n_samples_seen_: 599
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        i2OJfQb1MECBdwMmiXrpP2kKeYPBOok/I1vaDltGREDJoQKS0xP3P7bPVnjeGKI/e4QbTu7dTj+4
        42OVpUa6P4yNEBvTxxNAU79z6kWs3z/5zsRfmH3bP7z3ecGHZ94/0DNrKU904D8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        nvjZUbX4cUDTEnODS0nkPwrzez865CM/dhPqAxmxmUDO+5dqjKQAQLumQTYbeFQ/FB/5/CHGrT5e
        togKaZOFP/Dlaf5UdDhAw2Bx5mZZzz/C3d0S3p3HP7Me8n5t48w/fqM20Ovr0D8=
    with_mean: true
    with_std: true
