system_class:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    dZ3bXQ7C4j8=
  model:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - *id001
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 10
    _tol: null
    alpha: 0.0001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - !!python/object/apply:numpy.dtype
        args: [U119, 0, 1]
        state: !!python/tuple [3, <, null, null, null, 476, 4, 8]
      - false
      - !!binary |
        TgAAAG8AAABpAAAAcwAAAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1
        AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4A
        AABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAAAABf
        AAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAA
        AABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8AAABwAAAAbwAAAHIAAABvAAAAZAAA
        AF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAA
        XwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABj
        AAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAA
        AAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAA
        AHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8A
        AABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAA
        AGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYA
        AAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAA
        AGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABfAAAA
        XwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABf
        AAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8A
        AABwAAAAbwAAAHIAAABvAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAA
        AABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAA
        ADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAA
        cgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABm
        AAAAdQAAAHMAAABlAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkA
        AABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAXwAAAF8AAABwAAAAbwAA
        AHAAAAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAA
        cwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAA
        AF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAA
        YQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAx
        AAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAA
        AABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAA
        AGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABf
        AAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgA
        AABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAA
        AGkAAABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAA
        ADAAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAA
        ZQAAADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABv
        AAAAcgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABoAAAAYQAAAHIA
        AABkAAAAXwAAAHMAAABwAAAAaAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAA
        AGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAA
        bwAAAGQAAABfAAAAXwAAAHAAAABvAAAAcAAAADIAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABz
        AAAAcAAAAGgAAABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8A
        AABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAA
        AGEAAABsAAAAcAAAAG8AAABwAAAAMAAAAF8AAABoAAAAYQAAAHIAAABkAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAZQAAAHMAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1
        AAAAaQAAAG4AAABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAHUAAABuAAAA
        aQAAAGQAAABlAAAAbgAAAHQAAABpAAAAZgAAAGkAAABlAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11, 13]
      - *id001
      - false
      - !!binary |
        lFmVz9lLGcCUsQK6JIv5v6NejzOrBBNAUeWOgzuI8D+DIzJadgARQKJ8493QwSDABZ/bOqAy/L+i
        HkBkNpHYv09rfyEInPU/xqAyit6EA0BYlRF2c7UPQGnBVrmasglAaBzj6mWdAsBd1XqmEDIhwIH1
        njU5+TDA7lBBM6SKFMDyttkuMhIEwI/BM1pMaQhAsCirbpHhLkBUnbW8Maemv3rmefNBZC9Am5mQ
        Nry0FsDYuVeBnZEjwKo02NDlUybAWdPy+JJmJMC/dBU2jKYiQPZyEC8R3jtAouqzj7RREkADc1yc
        iT8hwARRGdUFzzJACvYZ9QXE+79vBLcLD0wYQH3nWJK0HxVAZsNrUjIJIcBwmac66gkHQOCdQMj/
        F/i/XamZSj667L8LhOUCfCv1v0yxi43MUfo/VqMgaaNZI0DmuoJj4+00wEjP8hNSNDDAAKH8eI0y
        McBAJl0OmLT4PzjM7EUaIui/sQmJ4oYWD8C76xEkQAkywJOgf8OuSOw/AgYeMTn3F8DZTMAqJyEY
        wGBuOmur+xfAQKE7eYuZF0C52D2hRPfzvwr3gdwXvSPANV6H24ac878mlFS8G68WwNJ/+SHrxwlA
        fc7IqZ2r8r9FhX49W0kiwFmJgRYySSbAB0BfGlS83j88AGplrJ8QwIaxdKVOmdW/ThwoAsjpCMCv
        hK0+P7gUQG05+Mo6VDZAnucJcds3OUBlIYZTtsIcwF6icKTQpCnA3kyWpTaoHcCbpXE/U2M0wOx7
        f9m7MSNA7LsNv6caNcBeJA8XBgv5P8fKH+91RxTAf+mNDDmfC8A/V3KR820SwJV2emvlxxVAWviZ
        /OprFkBaKqfgo1cmQPiv4udr8CzA7uOZyf62CcDa+4rqysQNwFTGrTlEAyXAjAy8hK1yL8D5vjic
        6Uk1wEwVhgzJWQdAyLFQAKMHIMD/khMJNHESwHhUZ73PahzAxEg38RjDIUAHT7PqYzQBwLapW7JP
        siDA6IL3DctuEUAJZxUc3/wAQET6Vyqk+dm/7jyXOLEc8r9wMzGjR5HVv+tnrxor+RLAAC63+pR1
        8L/pJoNPA8ccwFFMn+Pjfy5AeVzCMDIi778InB+qLJUqQCZh7GXZ3w/AJyqFSDskGcBAgzDqaLTs
        v4CWNbV8v+O/UivgYNSn9j8ugBiFRy4CwO711sYVr+c/Z9MZg3Aetj/pzA4dhdr9vy0i6G4kjxLA
        Juolrq7zEcACbAzQcX8SwA6aaSHwmRJAWDAQQOZcMcCW1B8lZ32rPz0WF08zNOS/f2HVeDPEGsD0
        wFX95dAUwJAvuTnyNChAiWU4dZnBHUDtO5mRXe9IQD4ICjU/4Oc/t+KPvrnx4b+Gt+mN0UIjwAgG
        X6AJYQ7AyhPGai5W9L9ItTjyxOItwAEQGuX5KhTAjqe/aAib1D89Dhl5ScrDP4ceEPdavApAZtaH
        DiwVD0BJEJDWBh4FQMcrAcYf3SxAIHi+RePC7D+1rA4iswsgwMflvpd72S3Aq+DQlOL2I8C1Y45n
        MEYYQA==
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [11]
      - *id001
      - false
      - !!binary |
        8NzWM7N8EMBDVrKORuZYwF8x1mFHZGHANc9M6fYdRsDo29Z1GxE7wElUfngqOmDAP/ouj4BOSsBb
        FcS/RDotwN5YXQq9XWDAQ5cjyg9IWsA8DrFXCsNXwA==
    l1_ratio: 0.5
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: 10
    n_iter: null
    n_iter_: 10
    n_jobs: 1
    penalty: l2
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 13201.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, l1_ratio: 0.5, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        Wu7f1BVyMUDMEhDGsvP1P97qCUEkU3s/hiip6KUXMkD6H6WUp+oIQOlMDbptTLs/t7xJ//nkYD8Y
        fQbXSU3CP5vO4uomPqi/0gLTFXd6279viqJ2hSbXvwMMulDhRdq/l7fYzXGp3D8=
    n_samples_seen_: 1440
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        DPAdFqoGL0AsMlTDr0HkPyFVwwNd44M/o5S97SkUQkCgk/PtIRHwP85tGveq9J4/uw/Cb9WoRT9C
        7vSDlSu5P6HLzJA00QlADI20s1wp2D9vfW1aBMPUP00iNV3XFtc/qX5yRhA+2T8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        Xlcq7uoUbkCoU/ATRaXZP31sV8qbuBg/m8gqwHdtlEA5wEg0ViLwP9pJG0IP8k0/MIen0iVSnT6A
        7bv6VMyDP3nKOdk51CRAe98nhEA+wj+eFS/c0/C6P+f3xePlqMA/oCgszXHpwz8=
    with_mean: true
    with_std: true
