accuracy:
  crystalline: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    t1askap/7z8=
  diffuse: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    FFcSEDSe7j8=
models:
  crystalline:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id001
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 5
    _tol: null
    alpha: 0.0001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - &id003 !!python/object/apply:numpy.dtype
        args: [b1, 0, 1]
        state: !!python/tuple [3, '|', null, null, null, -1, -1, 0]
      - false
      - !!binary |
        AAE=
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1, 13]
      - *id001
      - false
      - !!binary |
        o+fYONKYQUAR3k7Z0LEgQCJYX9FuhgHA5t27jfRpPkB6boLXdAEfwM9pskSscEHA9JqxP3Uox79r
        L9VnjrwwwExt0146ocS/xh21mHRTEMAAAAAAAAAAAJeQsSe4xwbAx5MuJPXQFEA=
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        gqZM7ECQ9b8=
    l1_ratio: 0.5
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: null
    n_iter: null
    n_iter_: 5
    n_jobs: 1
    penalty: elasticnet
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 9731.0
    tol: null
    verbose: 0
    warm_start: false
  diffuse:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id001
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPw==
    _max_iter: 5
    _tol: null
    alpha: 0.0001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [2]
      - *id003
      - false
      - !!binary |
        AAE=
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1, 13]
      - *id001
      - false
      - !!binary |
        GbBqf6HZJsAxZHuFDOQjwEQyZEBgBEbAdcFlJ99WRcD5a01oAbEcwA+RucfQvENAYqPHDRU2A8DH
        BQ5R3+YtQLSirqZZXQBA/OPFg+bSHkC6Q8GWqeFJwJhSJO1I1STAFvKRK2PLN8A=
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        eWaAmrw1QMA=
    l1_ratio: 0
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: null
    n_iter: null
    n_iter_: 5
    n_jobs: 1
    penalty: none
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 9731.0
    tol: null
    verbose: 0
    warm_start: false
scalers:
  crystalline:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        7YLQX3HHNUBMtBfWrj74P6ANFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOp8mmKfR7s/8MRKQRZ0YD/F
        QTehTlXCP8yJNwnPBNi/R91tOw8U2783w1LtxznXv5vlA+htBNq/X7r9Vd8Z3D8=
    n_samples_seen_: 1946
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        y3Hbe9lRNUCjsMwX+JjnP87cpyh9foM/lF7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
        SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7kGnZvSxNU/SjlhTjSF1z8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        80uymn1ofEBvx5vev2bhP+QLojdRwBc/2EgM2trtkEAU5ykWEuv1P3VsGnMEHE4/dtAE1BBAlj6p
        y0nS1XGDP9RELnJACFZAhH8MPCgAwD82AztpvQK5P4/zNAsenr0/AsrMq6VJwT8=
    with_mean: true
    with_std: true
  diffuse:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        7YLQX3HHNUBMtBfWrj74P6ANFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOp8mmKfR7s/8MRKQRZ0YD/F
        QTehTlXCP8yJNwnPBNi/R91tOw8U2783w1LtxznXv5vlA+htBNq/X7r9Vd8Z3D8=
    n_samples_seen_: 1946
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        y3Hbe9lRNUCjsMwX+JjnP87cpyh9foM/lF7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
        SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7kGnZvSxNU/SjlhTjSF1z8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        80uymn1ofEBvx5vev2bhP+QLojdRwBc/2EgM2trtkEAU5ykWEuv1P3VsGnMEHE4/dtAE1BBAlj6p
        y0nS1XGDP9RELnJACFZAhH8MPCgAwD82AztpvQK5P4/zNAsenr0/AsrMq6VJwT8=
    with_mean: true
    with_std: true
