pop0_site0_r0:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    TBoz9/YQtT8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        72FAnkql5T+7YGSf9BXaPwQJW6/egrC/VaXJ4yTPsT/ECJ75+XK4vy4pirbF99w//z8B4LDGwb+e
        sIXSL57VvzzqKIOianQ/LpUgFdIj3D8tyZ6T4uHYP1v+xTw2Pds/MNsclSQj3b9ZLG9nSd/Yv7s/
        jaZHb7e/JalTTz482r+8P/4G2g/Cvw==
    epsilon: 0.01
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        djzoLNV3O0A=
    l1_ratio: 0.95
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 17001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.01, l1_ratio: 0.95, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        grCOiXK8KkD53IOnzFTwP2W06K76FlM/C+L6TbA6CkC/VOVptV4FQJUH7VxC+7k/POdExugZXj/b
        xfq+DY6zP4X43zk1rgTAuXDSTmJD4r9LuxhSPZ/bvw5pZY6v9OC/pCp9GQ2T4z/SKo8YiPTFP7sb
        7xt4Aoc/i1shlFx1xj8kaYieYO+KPw==
    n_samples_seen_: 18
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        Kcmt8Yj8C0BOw6K6dNN6P8uNHy1WOCM/UmBbLnR85j8SxVoieJ3JP+8NDd0L/2M//DITpEw7MD+1
        +pjena6DP8w9dohkLxRAZgMSRcfUsT9+XdPb5EGwP8zIEMBkX7E/EvryzHoesj+fy7vzoy6jPyOF
        z+NadGo/OeCEX61GpD9LLQRyNJ9xPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        /MH9BvB5KEArjU/8En0GPzXzNgiTFlc+63GViwea3z9o8EGaEoGkPxTNLbed/dg+2ZDPDnV3cD5N
        f2qgKDYYP3z/QLYHdzlA3mseHTXfcz8oVeoX2YRwP9XbBtfu3HI/jsFRXc6EdD//fydYTf9WP6QA
        J8a63uU+DJ8mo+mxWT+L206Vf2jzPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal
pop0_site0_sigma:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    /SR/1UW52T8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAz4O6crTNUT8A
        AAAAAAAAAAAAAAAAAAAAcX1sIT9qOb8sML/eLhVWv6EtqieQnEW/EcwEA/60Fj/fOPkkAVlqP9bI
        EWKziU0/XhG5/n4scD/M2DuKLINrPw==
    epsilon: 0.001
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        KnF2L5XGrz8=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 17001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.001, l1_ratio: 0.15, loss: squared_loss, penalty: elasticnet}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        gbCOiXK8KkD43IOnzFTwP2W06K76FlM/C+L6TbA6CkC/VOVptV4FQJQH7VxC+7k/POdExugZXj/c
        xfq+DY6zP4b43zk1rgTAuXDSTmJD4r9LuxhSPZ/bvw5pZY6v9OC/pCp9GQ2T4z/TKo8YiPTFP7wb
        7xt4Aoc/i1shlFx1xj8jaYieYO+KPw==
    n_samples_seen_: 18
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        Ksmt8Yj8C0BNw6K6dNN6P8uNHy1WOCM/UmBbLnR85j8TxVoieJ3JP+4NDd0L/2M//DITpEw7MD+0
        +pjena6DP8w9dohkLxRAZgMSRcfUsT9/XdPb5EGwP8zIEMBkX7E/EvryzHoesj+fy7vzoy6jPyOF
        z+NadGo/OeCEX61GpD9LLQRyNJ9xPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        /cH9BvB5KEAqjU/8En0GPzbzNgiTFlc+6XGViwea3z9p8EGaEoGkPxLNLbed/dg+2JDPDnV3cD5M
        f2qgKDYYP3v/QLYHdzlA3WseHTXfcz8pVeoX2YRwP9XbBtfu3HI/jcFRXc6EdD//fydYTf9WP6QA
        J8a63uU+DZ8mo+mxWT+M206Vf2jzPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal
