pop0_site0_r0:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    6cgJf3aG7T8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        ifHMP53o27/0upnF103Yv1PYfj03A9w/Nh1JxquYxz/yC2nP2HfWv2g22bjxkuw/VzH43OqV1j/1
        QhWIkufwv1POOROoeKU/p2s4s7Sn4D+jFvAdzFrqP2dLtYFis+I/oaskHu853b985deIdly0P+bL
        kPGDbte/P/mkksBJ8r8pY8AESBfrPw==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        7l2XaP/7PUA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 37001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0.5, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        QkLIPVSxPUCczGtHYIABQJZqMDYBNWI/Ddu3tpEQKECNlkjBOMwJQDjSKHSgbbU/6pKuZ46yXD8j
        vMhsbGm4P6+qptVk1ca/NFyhMetX3L+XwvwrSBjWvzpi1+Qcgtq/Dhkn2eMi3j/SIEUkeqTBP2cv
        yPzAuqo/n/Amf1glwz/q8w3wO6CwPw==
    n_samples_seen_: 37
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        YYaRzp+II0AjSOj2DDriP8e5W/hf5DY/mPmazWbrJUAFrSgdECLfP29aryO1TZI/ckW0KWvVDj+V
        VZ2RA26RP9W2ORWhUiRA+v37zgo2tD+VENIxh+epPwcZnSa7EbI//V7a/vSGtj/w1OyQjB+lP6VW
        U+uKXsA/Taj1ZtQhmD/gqUj9rsDIPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        C22NLQrZV0CZN5PJb8PUP7EMMc5hYIA+XP8iOnUHXkDt4sR6I0rOP/C6xPdQ8DQ/LxE0Sri1LT79
        VIEGvPwyP+uTf2490FlAE21yjtGHeT9ir/JnTvhkPxqdIL34Z3Q/zrssE5S3fz8AMvIxD+NbP2fp
        qXtEv5A/oawGXuIyQj8RUYmzjiWjPw==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal__pop1_fcc__site0_spherical
pop0_site0_sigma:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    aMR5wK+fwT8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEkEFFU1vZ2/AAAAAAAAAACK
        85ks9ZuaPwAAAAAAAAAAB/7XvgY9ij9M0lhhxCWEP3sPK5kqCok/WqH+G1Fgi78AAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    epsilon: 0.01
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        MEz4zGwlxz8=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 37001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.01, l1_ratio: 0.15, loss: huber, penalty: elasticnet}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        QELIPVSxPUCczGtHYIABQJdqMDYBNWI/Dtu3tpEQKECOlkjBOMwJQDfSKHSgbbU/6pKuZ46yXD8j
        vMhsbGm4P7mqptVk1ca/NFyhMetX3L+XwvwrSBjWvzpi1+Qcgtq/DBkn2eMi3j/TIEUkeqTBP2gv
        yPzAuqo/oPAmf1glwz/q8w3wO6CwPw==
    n_samples_seen_: 37
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        YYaRzp+II0AjSOj2DDriP8m5W/hf5DY/l/mazWbrJUAFrSgdECLfP29aryO1TZI/ckW0KWvVDj+V
        VZ2RA26RP9W2ORWhUiRA+v37zgo2tD+UENIxh+epPwcZnSa7EbI//V7a/vSGtj/w1OyQjB+lP6VW
        U+uKXsA/S6j1ZtQhmD/gqUj9rsDIPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        C22NLQrZV0CZN5PJb8PUP7QMMc5hYIA+Wv8iOnUHXkDt4sR6I0rOP++6xPdQ8DQ/LxE0Sri1LT79
        VIEGvPwyP+uTf2490FlAE21yjtGHeT9gr/JnTvhkPxqdIL34Z3Q/zrssE5S3fz8AMvIxD+NbP2bp
        qXtEv5A/nqwGXuIyQj8RUYmzjiWjPw==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal__pop1_fcc__site0_spherical
pop1_a:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    RB5fgLhY/z8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        kflhCdwZuT+YgaWRCxHkvwrfWasrv+k/IWaUM/LQw7/MXb1ERabsP3mjy+YKxec/Gb/n6oX64z8o
        tbdKQHADwL8mxDsRXqy//LpEzptY0z8bB7myyC7pP7h3CoMX4dk/1DTGJWOvyb+eZLhqKinHv1tr
        0Ld01Mm/SM3Bbolt/b82EWf/JR7+Pw==
    epsilon: 0
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        SG7FWomPXEA=
    l1_ratio: 0.95
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 37001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0, l1_ratio: 0.95, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        QkLIPVSxPUCczGtHYIABQJZqMDYBNWI/D9u3tpEQKECOlkjBOMwJQDbSKHSgbbU/65KuZ46yXD8j
        vMhsbGm4P7GqptVk1ca/MlyhMetX3L+YwvwrSBjWvzti1+Qcgtq/EBkn2eMi3j/TIEUkeqTBP2Yv
        yPzAuqo/oPAmf1glwz/q8w3wO6CwPw==
    n_samples_seen_: 37
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        YoaRzp+II0AjSOj2DDriP8m5W/hf5DY/mPmazWbrJUAFrSgdECLfP29aryO1TZI/cUW0KWvVDj+V
        VZ2RA26RP9S2ORWhUiRA+v37zgo2tD+TENIxh+epPwcZnSa7EbI//F7a/vSGtj/w1OyQjB+lP6ZW
        U+uKXsA/TKj1ZtQhmD/fqUj9rsDIPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        DG2NLQrZV0CZN5PJb8PUP7QMMc5hYIA+XP8iOnUHXkDt4sR6I0rOP++6xPdQ8DQ/LRE0Sri1LT7+
        VIEGvPwyP+qTf2490FlAE21yjtGHeT9fr/JnTvhkPxudIL34Z3Q/zLssE5S3fz8AMvIxD+NbP2jp
        qXtEv5A/n6wGXuIyQj8QUYmzjiWjPw==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal__pop1_fcc__site0_spherical
pop1_site0_r:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Xp7zvEOdBUA=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        PlZuiQqcsr8OHGkprgTMvy6QVX1/NMw/SgYT5Zxqpb+olNxnzbHYPyFWSWmtRdM/z+GGbI2qkr/o
        +OPZe7vrvwSkMVckqoe/g+q40f44mj+nCDKb0mPIP3eCHwGB6K4/6bmVS/Bhgj8cFQezzeegv25G
        W3xOp7i/aSP3yjcU4r/FkYU8jfjiPw==
    epsilon: 0.001
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        NeRJ5RLNP0A=
    l1_ratio: 0
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 37001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.001, l1_ratio: 0, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        QkLIPVSxPUCdzGtHYIABQJZqMDYBNWI/Ddu3tpEQKECNlkjBOMwJQDbSKHSgbbU/6pKuZ46yXD8j
        vMhsbGm4P7CqptVk1ca/NFyhMetX3L+XwvwrSBjWvzti1+Qcgtq/Dhkn2eMi3j/RIEUkeqTBP2cv
        yPzAuqo/ofAmf1glwz/q8w3wO6CwPw==
    n_samples_seen_: 37
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        YoaRzp+II0AkSOj2DDriP8m5W/hf5DY/mPmazWbrJUAErSgdECLfP29aryO1TZI/cUW0KWvVDj+V
        VZ2RA26RP9W2ORWhUiRA+v37zgo2tD+UENIxh+epPwcZnSa7EbI//V7a/vSGtj/w1OyQjB+lP6VW
        U+uKXsA/TKj1ZtQhmD/fqUj9rsDIPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        DG2NLQrZV0CaN5PJb8PUP7QMMc5hYIA+XP8iOnUHXkDr4sR6I0rOP++6xPdQ8DQ/LRE0Sri1LT79
        VIEGvPwyP+yTf2490FlAFG1yjtGHeT9hr/JnTvhkPxudIL34Z3Q/zrssE5S3fz8AMvIxD+NbP2fp
        qXtEv5A/n6wGXuIyQj8QUYmzjiWjPw==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_spherical_normal__pop1_fcc__site0_spherical
