pop0_r_hard:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    eIov6Pot8z8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAADAbjtIJhSvv/8Ofam2orI/evUk7lTdpz+grzvYUX3Jv3y0Ag8NJ8U/gIUllRVZtD8o
        RdD0fJLIvwAAAAAAAAAAj9uq35fDoD8AAAAAAAAAAAAAAAAAAAAAorP497uztr/lmW9pPiukv1Ej
        8ple1qM/AAAAAAAAAAAAAAAAAAAAAA==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        oVn/VDP5GUA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 89001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0.5, loss: huber, penalty: elasticnet}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        R4xhu13YC0CBpN0zuk71P6EzdbfljZk/lcFNsochJUCYFYJGKBkFQGYe+T8AAcQ/iAQzQet4Zz+y
        c6YOg6fSP134b8WRBtY/LXsyQL/O1L9oTJ8I+kHXvwE65rVBzNW/dnMpANrd0z/tIdtFTKDHP2+U
        rgYQh8Q/JzEkxyRYxT/1sBcVBKrTPw==
    n_samples_seen_: 92
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        gk0Denbl9z+qHzTeBMTVPyrp65WbbIQ/ipzknwsCFECnUGNCcMf0P+zlylns7pE/l/WEwfgwYD/m
        k4ZApKWfP/p5Ukf/zPY/71K5BzGu2j9yJaRlKB3ZP/t5CuJoRNo/WFPa8Wn82j9gqk1DMO7EP5rh
        FcUdMtE/JeASthGl3z859n1pwtn/Pw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        WrTNuEfYAUBOS44+7pu9P+ulHjFmEho/mfKrUh0FOUCZUn+hTvz6P6fX4QOmGTQ/LYGuZodi0D5I
        QCmmR0xPP50800AAPwBA1EUM4sM+xj9jszuwqbXDPz92aa68j8U/XLgCL/PBxj9qBaaEUmGbPxSs
        FT0ce7I/bwJ0zyVLzz/c6beFsrMPQA==
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
pop0_site0_D:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AAAAAAAA8H8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.0001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        TWS7ex3bMj/haz98qE0CP9O8Y6MwnRo//vzBwi6cFj//RDOmRUwXv9zgxKtyZNi+qwS3sdy06b7c
        6maOy8s9P5NpGp0Fteu+nhNs1RQZAT83oFvm109Av6BZROvefCG/k2xQvf+1Kb8DeBudwmj+vuXs
        ITDhCPi+RDZWLobMMT/m5F51D8kyPw==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        93IbBAAAEEA=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: none
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 89001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        R4xhu13YC0CApN0zuk71P6MzdbfljZk/lsFNsochJUCZFYJGKBkFQGce+T8AAcQ/iAQzQet4Zz+y
        c6YOg6fSP1/4b8WRBtY/LnsyQL/O1L9nTJ8I+kHXvwE65rVBzNW/eHMpANrd0z/rIdtFTKDHP3CU
        rgYQh8Q/KDEkxyRYxT/2sBcVBKrTPw==
    n_samples_seen_: 92
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        gk0Denbl9z+pHzTeBMTVPynp65WbbIQ/ipzknwsCFECmUGNCcMf0P+zlylns7pE/l/WEwfgwYD/n
        k4ZApKWfP/t5Ukf/zPY/71K5BzGu2j9yJaRlKB3ZP/t5CuJoRNo/WFPa8Wn82j9fqk1DMO7EP5rh
        FcUdMtE/JuASthGl3z869n1pwtn/Pw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        WrTNuEfYAUBLS44+7pu9P+qlHjFmEho/mfKrUh0FOUCWUn+hTvz6P6fX4QOmGTQ/LYGuZodi0D5K
        QCmmR0xPP54800AAPwBA00UM4sM+xj9jszuwqbXDPz92aa68j8U/XbgCL/PBxj9nBaaEUmGbPxWs
        FT0ce7I/cgJ0zyVLzz/f6beFsrMPQA==
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
pop0_site0_rg:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    +YEEXErf7D8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        wU8+mEhhzz+7mvuaBpGwvwAAAAAAAAAAomeWf/bXsD8TH3dGqK2yP+MJRCdD4sY/57r1sRRbwL8A
        AAAAAAAAACDbqaydSs4/FT6k7WwFzr+MG6a8OkXHv22ay2E/Nc2/Ygf/YJp+0D+0yKB2fN25PwAA
        AAAAAAAA98zecMyjo78=
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        3gg/paQqFUA=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 89001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0.15, loss: squared_loss, penalty: l1}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        R4xhu13YC0B/pN0zuk71P6AzdbfljZk/lsFNsochJUCZFYJGKBkFQGYe+T8AAcQ/hwQzQet4Zz+z
        c6YOg6fSP1/4b8WRBtY/LXsyQL/O1L9nTJ8I+kHXvwE65rVBzNW/d3MpANrd0z/RpUkatkgWQOFa
        NPaUofQ/D4dw+8Dxtj8=
    n_samples_seen_: 92
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        g00Denbl9z+qHzTeBMTVPynp65WbbIQ/ipzknwsCFECmUGNCcMf0P+zlylns7pE/l/WEwfgwYD/m
        k4ZApKWfP/p5Ukf/zPY/71K5BzGu2j9yJaRlKB3ZP/t5CuJoRNo/WFPa8Wn82j9isix38/kGQNhG
        OnsTTNw/uqgD2GHFsj8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        W7TNuEfYAUBNS44+7pu9P+qlHjFmEho/mfKrUh0FOUCYUn+hTvz6P6fX4QOmGTQ/LYGuZodi0D5I
        QCmmR0xPP50800AAPwBA1EUM4sM+xj9jszuwqbXDPz92aa68j8U/XLgCL/PBxj+ReAggT38gQPos
        O/TWBck/T+zFIZ8Fdj8=
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
pop0_v_fraction:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    UG5W8Fn27z8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDULPK+RGA/AAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf6HGQ8uCDvwAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
    epsilon: 0.1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        HujH73jRzj8=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 90001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.1, l1_ratio: 0, loss: huber, penalty: l1}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        R4xhu13YC0B/pN0zuk71P6EzdbfljZk/lMFNsochJUCYFYJGKBkFQGYe+T8AAcQ/iAQzQet4Zz+z
        c6YOg6fSP174b8WRBtY/LXsyQL/O1L9oTJ8I+kHXvwE65rVBzNW/dnMpANrd0z/tIdtFTKDHP3GU
        rgYQh8Q/KDEkxyRYxT/1sBcVBKrTPw==
    n_samples_seen_: 92
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        gk0Denbl9z+qHzTeBMTVPynp65WbbIQ/i5zknwsCFECmUGNCcMf0P+zlylns7pE/l/WEwfgwYD/m
        k4ZApKWfP/t5Ukf/zPY/71K5BzGu2j9xJaRlKB3ZP/t5CuJoRNo/WFPa8Wn82j9fqk1DMO7EP5rh
        FcUdMtE/JeASthGl3z859n1pwtn/Pw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        WrTNuEfYAUBOS44+7pu9P+qlHjFmEho/mvKrUh0FOUCYUn+hTvz6P6bX4QOmGTQ/LoGuZodi0D5I
        QCmmR0xPP54800AAPwBA1EUM4sM+xj9iszuwqbXDPz92aa68j8U/XbgCL/PBxj9oBaaEUmGbPxWs
        FT0ce7I/bwJ0zyVLzz/d6beFsrMPQA==
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
