pop0_r_hard:
  cross_valid_results:
    experiments: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10]
      - &id003 !!python/object/apply:numpy.dtype
        args: [O8, 0, 1]
        state: !!python/tuple [3, '|', null, null, null, -1, -1, 63]
      - false
      - [Reaction_H, R7, Reaction_G, Reaction_D, Reaction_C, R3, Reaction_E, R13,
        R1, R12]
    labels_std: 41.345319595715864
    normalized_mean_abs_error: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args: [f8, 0, 1]
      state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
    - !!binary |
      byfrpSy35z8=
    normalized_mean_abs_error_by_experiments:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        6BWHPL3WsT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NusLMgQE4z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        GCAZNwzLrT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        pi5Hcwp9sD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        KKcMZgYSuj8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        NtcGDry9uD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        v7EPEMG2uD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        y+mjINmd0D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        +ZeiNfRW3z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        tROCLitSFkA=
    number_of_experiments: 10
    test_training_split: by experiments
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        sZqqUA2jl7+kY9EO+zKqvwAAAAAAAAAAIPW0MHTx8z8AAAAAAAAAAAAAAAAAAAAAY+DOqnX85j8f
        lyKQhaHkvwAAAAAAAAAAAAAAAAAAAADx9AHGqOiDv+TtCqyN/uW/GxgJBdluzL8AAAAAAAAAAAAA
        AAAAAAAAYHiW3Rasxb8AAAAAAAAAACmgpk4VLr+/AAAAAAAAAAAE71wRx9DRvwAAAAAAAAAAAAAA
        AAAAAAA=
    epsilon: 0.1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        Jig9eyfiD0A=
    l1_ratio: 0.95
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 127001.0
    tol: null
    verbose: 0
    warm_start: false
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        WxbZSWkQEEAYkl1bP6T7PyTUpOluVfI/SeImuqHnFkBu4xKcZygbQArZTLvmPCBAwMs4OlcdwD8N
        uqwBLcxyP/23qTp5atE/hPOvZhCm0T8KR9bQL2zdv5nIDvTp3ty/6l2sQJN13b+oZ6bit0ndP0u1
        K7Ymf7E/TDfkOxYdtT8PqCqwnwVlPzRqjE7japE/Hr1Q9rzysT8gwOlit366P59xYAWMpl4/QAP/
        NH1rlD8=
    n_samples_seen_: 129
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        YTIFxHEbCkBiVxx9l3zsP7pOk5/ywbs/2DEEI3mVAkAdVe9uSrUBQGkyFCiq0gpAjVh3YaZImT8c
        nXGZ0IxpP1tTz6K9dZ8/m7scdspnpj8yVWVT6avRP0L1Hl14/NE/MRd8TIW70T9AWAt9aZ7RP+6l
        SvLdVsQ/zh8FWyowtz8BhpZeCHaEP8J6cZb2JaU/MM7RCq+XxD/c+Sn+9ITRP3LG3fdfvH0/y6P2
        1xdrvT8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        uK8XaLBMJUA1W8gz7lvpP28GHevgE4g/M8CK8sSVFUDqwCRRRJkTQAml912/eyZAyidi6Cj6Qz9A
        9U+WcWbkPgAMjKLQ7U4/l5+BDQ5gXz+hedjphoSzP0mP4JgPOLQ/4g66AhGnsz+eONWPwGazP+4E
        rnsC25k/CH0gYoXNgD8C3O+neyoaP7wGOl4B9Fs/QbhzmtOAmj9VPyJ12S6zP8A0AtrCoQs/aw71
        noELiz8=
    with_mean: true
    with_std: true
pop0_site0_rg:
  cross_valid_results:
    experiments: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10]
      - *id003
      - false
      - [Reaction_D, Reaction_H, Reaction_C, R3, R7, Reaction_E, R13, Reaction_G,
        R12, R1]
    labels_std: 10.71422029982525
    normalized_mean_abs_error: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      ZL+xPcDL5z8=
    normalized_mean_abs_error_by_experiments:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        X+5P8e6SzD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        9SC6D7GkzD8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        WERZwlRQ1T8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        bJNwmHrXtz8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        MJRG9FZqnT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        2M7/nrsb0j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        9Yl4kzt91D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Zy1QR5Or0D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        nqHwHv4UFkA=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        PvOiId87wz8=
    number_of_experiments: 10
    test_training_split: by experiments
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        olTeBSptzj8fbwiRKdfQP1Ace7d3+46/AAAAAAAAAABFm0oGqIGjPyYJeZafP7u/AAAAAAAAAAAA
        AAAAAAAAAAhWrkxG496/xGits3aqwb8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAA=
    epsilon: 0.1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        oERudRgMCUA=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 126001.0
    tol: null
    verbose: 0
    warm_start: false
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        WxbZSWkQEEAXkl1bP6T7PyTUpOluVfI/SeImuqHnFkBu4xKcZygbQArZTLvmPCBAwMs4OlcdwD8M
        uqwBLcxyP/63qTp5atE/hfOvZhCm0T8KR9bQL2zdv5nIDvTp3ty/7F2sQJN13b+oZ6bit0ndP0u1
        K7Ymf7E/SzfkOxYdtT8PqCqwnwVlPzRqjE7japE/Hr1Q9rzysT8gwOlit366P55xYAWMpl4/QQP/
        NH1rlD8=
    n_samples_seen_: 129
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        YDIFxHEbCkBhVxx9l3zsP7lOk5/ywbs/2DEEI3mVAkAdVe9uSrUBQGkyFCiq0gpAjFh3YaZImT8c
        nXGZ0IxpP1xTz6K9dZ8/m7scdspnpj8yVWVT6avRP0L1Hl14/NE/MRd8TIW70T9BWAt9aZ7RP+6l
        SvLdVsQ/zx8FWyowtz8BhpZeCHaEP8J6cZb2JaU/MM7RCq+XxD/c+Sn+9ITRP3LG3fdfvH0/y6P2
        1xdrvT8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        t68XaLBMJUA0W8gz7lvpP24GHevgE4g/M8CK8sSVFUDqwCRRRJkTQAml912/eyZAySdi6Cj6Qz9A
        9U+WcWbkPgIMjKLQ7U4/l5+BDQ5gXz+hedjphoSzP0mP4JgPOLQ/4g66AhGnsz+fONWPwGazP+4E
        rnsC25k/CX0gYoXNgD8C3O+neyoaP74GOl4B9Fs/QbhzmtOAmj9UPyJ12S6zP8A0AtrCoQs/aw71
        noELiz8=
    with_mean: true
    with_std: true
pop0_v_fraction:
  cross_valid_results:
    experiments: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10]
      - *id003
      - false
      - [Reaction_C, R7, R3, Reaction_E, R13, R1, Reaction_D, Reaction_G, Reaction_H,
        R12]
    labels_std: 0.15189075189684817
    normalized_mean_abs_error: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      1Q9t25/g8T8=
    normalized_mean_abs_error_by_experiments:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        SYklQZLW8z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        USAY+35HxT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        AJ5R1c80pT8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        BvXVNd6n8T8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        01jVzAUd+j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        JrMyAcey6z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        Ns0+FbAP8j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        vP9odkca+z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        CbAXYQXI8D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - *id001
      - !!binary |
        0q+FwWgGAkA=
    number_of_experiments: 10
    test_training_split: by experiments
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAA=
    epsilon: 0.001
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        SgC/DGY+sT8=
    l1_ratio: 0.95
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 127001.0
    tol: null
    verbose: 0
    warm_start: false
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        WxbZSWkQEEAYkl1bP6T7PyTUpOluVfI/SeImuqHnFkBu4xKcZygbQArZTLvmPCBAwMs4OlcdwD8M
        uqwBLcxyP/23qTp5atE/g/OvZhCm0T8KR9bQL2zdv5nIDvTp3ty/7F2sQJN13b+oZ6bit0ndP0u1
        K7Ymf7E/SzfkOxYdtT8OqCqwnwVlPzRqjE7japE/Hr1Q9rzysT8iwOlit366P59xYAWMpl4/QQP/
        NH1rlD8=
    n_samples_seen_: 129
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        YTIFxHEbCkBhVxx9l3zsP7pOk5/ywbs/2TEEI3mVAkAdVe9uSrUBQGgyFCiq0gpAjVh3YaZImT8c
        nXGZ0IxpP1xTz6K9dZ8/m7scdspnpj8yVWVT6avRP0L1Hl14/NE/MRd8TIW70T9AWAt9aZ7RP+6l
        SvLdVsQ/zx8FWyowtz8BhpZeCHaEP8J6cZb2JaU/MM7RCq+XxD/c+Sn+9ITRP3LG3fdfvH0/zKP2
        1xdrvT8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [22]
      - *id001
      - false
      - !!binary |
        uK8XaLBMJUA0W8gz7lvpP3AGHevgE4g/NMCK8sSVFUDqwCRRRJkTQAil912/eyZAyidi6Cj6Qz9A
        9U+WcWbkPgIMjKLQ7U4/l5+BDQ5gXz+hedjphoSzP0iP4JgPOLQ/4g66AhGnsz+eONWPwGazP+0E
        rnsC25k/CX0gYoXNgD8B3O+neyoaP70GOl4B9Fs/QbhzmtOAmj9UPyJ12S6zP8A0AtrCoQs/bQ71
        noELiz8=
    with_mean: true
    with_std: true
