pop0_site0_D:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAAAA8H8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.0001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        oPuq4qHMKj/uVLnUd0Yrv/loVCbPOic/R7VPQJhJ/r6B4hG7AyIXP/UL4kkdjTY/AAAAAAAAAACC
        SGArT3A5v4j3zDu7HrK+JzEDbtBgEz8ABxL4z6IfP0JxGfA5RBY/9hlG1y11EL9nklXLt7frvlCy
        0Kwi6eW+sNklgDNgBb/i1lDUUYPCPg==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        TC/4AAAAEEA=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: none
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        97lK2QdATUClRu0gQKIHQGW1GBe7uWg/dQBR8vE/ZUC9VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8h
        X11s8E25P1r3MUmgbsA/yNN3zKHQ0r9U7OOa1DPOv0VQCRM3udG/F+Bi6CzZ0z/021LHi13BP65+
        ivC/24U/Koq4rM+uwT8M04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEBxPtMAXw3dP8y34prq0jI/7Job3pwLUkDdOHUI0krUP0XRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+WcWIeXp6sP2q1+13VLrI/Nl2jsKF2tT+/4pgn5k9+P5qq
        zjKwrGE/hMMXYjq4fT8K9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC1mcnHQWDKPyfVTzhsJXY+rnlxYSlatECBaLj2ary5P1hc2M4rNfw+AAAAAAAAAAAF
        OZdGG9UAP3fUWY8tUz8/G11RpEt+eD+IJa13NJhpP/cXcCnpqXQ/wjj8BtjKfD9shRkJl7YMPz/k
        zz8+htM+a6idcQ6aCz/xB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop0_site0_rg:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    J6hn/2gw5D8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAAACppAO/qCDP1w/57D7l9A/tN6YQotZ2r9Lj3gVv762vwAAAAAAAAAAAAAAAAAAAABt
        uDdPDD6pPx5BqZc6u8S/KyhDINgkuD8W8z3hvPyvP7FmMKOWPrY/AmHFB9ASur+rLsHDmP/LP84A
        dvgbFL4/TLkbk+ds0D8=
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        kq+PmFW/D0A=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0.15, loss: huber, penalty: l1}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        97lK2QdATUCkRu0gQKIHQGa1GBe7uWg/dQBR8vE/ZUC9VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8i
        X11s8E25P1r3MUmgbsA/yNN3zKHQ0r9T7OOa1DPOv0VQCRM3udG/FeBi6CzZ0z92RPV459GSQNmg
        nDotOeI/wstzr2lMrD8=
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEByPtMAXw3dP8y34prq0jI/7Job3pwLUkDdOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4NMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/NV2jsKF2tT8FQikxiXFrQGiJ
        YVA4Lb4/IHEhkl9TmT8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC4mcnHQWDKPyfVTzhsJXY+rnlxYSlatECBaLj2ary5P1Vc2M4rNfw+AAAAAAAAAAAF
        OZdGG9UAP3TUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wTj8BtjKfD8IAC1WKonnQBUO
        fH0JdYw/frw3jR4LRD8=
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop1_site0_r0:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    Yar2C2v+4j8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        pau0iYFC6z/F2jxTMd3xvyyKBRuAKOY/rahy2uYO1D9FhM6RyuDgv0zetHSACPO/AAAAAAAAAABb
        U1gnSUf6v3dJvakgT9c/Br8sUyAslT8XcvbrZPS2P5xGdmPx86I/m4wKpjvmcb8H3fgT7639v2XD
        +KQtF8q/Jl1C63aVAsCbJKyvkkfEPw==
    epsilon: 0.1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        UPKqJxoAQ0A=
    l1_ratio: 0
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.1, l1_ratio: 0, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        +LlK2QdATUClRu0gQKIHQGW1GBe7uWg/dQBR8vE/ZUC9VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8g
        X11s8E25P1v3MUmgbsA/yNN3zKHQ0r9T7OOa1DPOv0ZQCRM3udG/F+Bi6CzZ0z/021LHi13BP69+
        ivC/24U/KYq4rM+uwT8M04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEBxPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0XRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/Nl2jsKF2tT+/4pgn5k9+P5qq
        zjKwrGE/hMMXYjq4fT8J9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC1mcnHQWDKPyfVTzhsJXY+rnlxYSlatECCaLj2ary5P1lc2M4rNfw+AAAAAAAAAAAF
        OZdGG9UAP3fUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/cXcCnpqXQ/wjj8BtjKfD9shRkJl7YMPz/k
        zz8+htM+a6idcQ6aCz/vB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop1_site0_sigma:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    AnbiIg0h3T8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        hCF/m5QNcz/7k+RryC+XP01pKbk3toO/80F2IXNdeb+QrGJjLaaEP0p3MNfejow/AAAAAAAAAABH
        L49Eq36HPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADPzPUdY4iSPwAA
        AAAAAAAA9pQG94yWjz8AAAAAAAAAAA==
    epsilon: 0.01
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        /TT7urtLpT8=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.001, epsilon: 0.01, l1_ratio: 0.5, loss: huber, penalty: elasticnet}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        97lK2QdATUClRu0gQKIHQGe1GBe7uWg/dQBR8vE/ZUC9VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8k
        X11s8E25P1r3MUmgbsA/x9N3zKHQ0r9T7OOa1DPOv0ZQCRM3udG/FeBi6CzZ0z/121LHi13BP69+
        ivC/24U/Koq4rM+uwT8M04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEBxPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4NMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/NV2jsKF2tT+/4pgn5k9+P5qq
        zjKwrGE/hMMXYjq4fT8J9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        GDuOqbxaYkC1mcnHQWDKPyfVTzhsJXY+rnlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3TUWY8tUz8/G11RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wDj8BtjKfD9shRkJl7YMPz/k
        zz8+htM+a6idcQ6aCz/vB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop2_a:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    TfjRyIcf+T8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        9FOSmFxe2z+mZ8e5dkvdvz8t3nYhyeA/wsU8cPDScb+JSpcUQ+PSv0ojukX2Veu/AAAAAAAAAADA
        MW3YHjDqvymSZ7Uy1Ls/LNROXTC7zD+o43SvYRnSPwVY3rhhf84/OQPBNmT0yr+YI3nSr9H1v43d
        W7zuGdG/gajqWqU4+L8eQ8Bzct+9Pw==
    epsilon: 0.001
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        FueX1EzpXEA=
    l1_ratio: 0.95
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.001, l1_ratio: 0.95, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        97lK2QdATUClRu0gQKIHQGa1GBe7uWg/dwBR8vE/ZUC9VzF1uQIQQBcH6rUUvLg/jghm0yKNYz8h
        X11s8E25P1v3MUmgbsA/yNN3zKHQ0r9S7OOa1DPOv0VQCRM3udG/F+Bi6CzZ0z/021LHi13BP69+
        ivC/24U/Koq4rM+uwT8M04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEByPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/Nl2jsKF2tT/A4pgn5k9+P5qq
        zjKwrGE/g8MXYjq4fT8J9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC3mcnHQWDKPyfVTzhsJXY+rXlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3fUWY8tUz8/G11RpEt+eD+JJa13NJhpP/cXcCnpqXQ/wjj8BtjKfD9uhRkJl7YMPz/k
        zz8+htM+aaidcQ6aCz/vB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop2_site0_r:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    usTfwSJq9z8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        5637N0h2uD9ORYnKO2DTv5GRrwaBIrI/eqG8elC7kz/pA7ZqpsKdP6Xjb7gyXOG/AAAAAAAAAADb
        ZuA1U6K1v5LQ75tEQ52/yK0mMKJ8pz87iq5iPuSuPwbXUzJkO6k/jilM6Ee4pb/ri3UjlZHWv9cz
        KjQNN6O/dxHsPqn62L/QqRNVQKlNvw==
    epsilon: 0.001
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        kRvAEJqKQEA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.001, l1_ratio: 0.5, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        +LlK2QdATUClRu0gQKIHQGe1GBe7uWg/eABR8vE/ZUC8VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8g
        X11s8E25P1v3MUmgbsA/x9N3zKHQ0r9T7OOa1DPOv0ZQCRM3udG/F+Bi6CzZ0z/021LHi13BP69+
        ivC/24U/K4q4rM+uwT8L04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEByPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/NV2jsKF2tT+/4pgn5k9+P5qq
        zjKwrGE/hcMXYjq4fT8J9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC4mcnHQWDKPyfVTzhsJXY+rXlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3fUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/cXcCnpqXQ/wTj8BtjKfD9shRkJl7YMPz/k
        zz8+htM+bKidcQ6aCz/vB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
