pop0_site0_D:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAAAA8H8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.0001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        nmNXN0ERND82d2NIDpAFP7e1q2w3zCY/t+qfCeMgAz9CHktCIRjSvo+mCCwyMui+QCBKHBKT8r7l
        WJ0EaK83P6xFimFUiui+sJGxL+LmID+VexKWOlJHv2RdeJah8iC/NKsfy1BiOb/5fEk2pwn7PukX
        LlUxFAI/fvCPIKV9wL6gLsoh9+vCvg==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        /uhaBgAAEEA=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: none
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 106001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        loaW2aG4C0C7ah7zDij1P1gBe+xwEZk/Yzkj+c28JUAvE27sOqcGQEb+sQH178M/xh1BrzxVZz9T
        M6XAyZDSP64qxFbt6dQ/bfYNapV/1r9LuQGY/dvYv6J1VrkLd9e/RzOerpCQ1T/uXYgbyzbJPwKH
        04xGQcU/gXdPDPmJzD+XAMb8nB/bPw==
    n_samples_seen_: 106
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        so5x303a9z+OzEWBD+DUPxCWJYq/TYQ/hrbpl6CJE0BH+H08TuT3P2cVB4qRZpE/Z6AtXU3eXj+f
        W4TSt8SfPy6bQnbFQvU/d6EwlUqK2j9jX4Kt0uzYP498xBlJHNo/qIlxEmPc2j+gfPIIJ/zEPyLw
        75ytddA/YvwuC7y44z8hgqSDaqkCQA==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        wyn1NqHHAUA5KGF1aDy7P9aX5KXYwxk/uHdAPX3bN0BQX5JSjdYBQDPCGsqG7DI/Tm/dYNnGzT4Z
        PNN33YlPP2twA/1cQPw/ip5j1g4Dxj8Q2y2tFGrDP+hfc8oPTsU//9Jo0Q6Mxj+KSVdk54WbPyTt
        Ury87rA/7tYyiBNP2D+GLBSFMcQVQA==
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
pop0_site0_rg:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    LFkRY2Wu6T8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        pyWKzRYv1T8dEcx7fhixvwAAAAAAAAAAKneWzY9Fuz/QL4gPsVyUPxr9FizJMc4/o4x9xEMiwL8A
        AAAAAAAAAAvXUlMk0Mg/NzQ9ERPQ1b+qCJc9pUyZv8RaRW+RbtC/fQ7pQmmF3D8R+3DlHBSNP3VV
        hzzfipm/hdDKNJE5n78=
    epsilon: 0
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        arEsBr1HFUA=
    l1_ratio: 0.95
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 103001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0, l1_ratio: 0.95, loss: squared_loss, penalty: l1}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        loaW2aG4C0C7ah7zDij1P1gBe+xwEZk/Yzkj+c28JUAvE27sOqcGQEb+sQH178M/xh1BrzxVZz9T
        M6XAyZDSP64qxFbt6dQ/bfYNapV/1r9LuQGY/dvYv6J1VrkLd9e/RzOerpCQ1T8Z48Fr9cIXQHCb
        A+2SLfQ/h+p16Nx4tz8=
    n_samples_seen_: 106
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        so5x303a9z+OzEWBD+DUPxCWJYq/TYQ/hrbpl6CJE0BH+H08TuT3P2cVB4qRZpE/Z6AtXU3eXj+f
        W4TSt8SfPy6bQnbFQvU/d6EwlUqK2j9jX4Kt0uzYP498xBlJHNo/qIlxEmPc2j+F7Jpg2coIQH/P
        ID7HMNw/o0dHScivsz8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        wyn1NqHHAUA5KGF1aDy7P9aX5KXYwxk/uHdAPX3bN0BQX5JSjdYBQDPCGsqG7DI/Tm/dYNnGzT4Z
        PNN33YlPP2twA/1cQPw/ip5j1g4Dxj8Q2y2tFGrDP+hfc8oPTsU//9Jo0Q6Mxj8KrhDvSzUjQL5a
        TAen1cg/qGoX5QY5eD8=
    with_mean: true
    with_std: true
  system_class: pop0_hard_spheres__site0_guinier_porod
