pop0_site0_D:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAAAA8H8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.0001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        7it79H10ET+3KIsKvLsiv3lhQlkFDRQ/FFpUOO//CD9Qawit90Aov17GamNEUh8/AAAAAAAAAAC4
        RxuQbdMavzLgp1D7Wh4/fW4QHqmNGz8Cexs/U+oYP04ozo/B8xo/JYP0Q4sxHL+guSpziKEbv6uS
        +6IlqRI/l3RDQ2A9MT952AJ5yF/0vg==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        SRjFAwAAEEA=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: none
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        9blK2QdATUCiRu0gQKIHQGa1GBe7uWg/dQBR8vE/ZUC8VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8g
        X11s8E25P1v3MUmgbsA/yNN3zKHQ0r9U7OOa1DPOv0ZQCRM3udG/F+Bi6CzZ0z/021LHi13BP69+
        ivC/24U/Koq4rM+uwT8N04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEBxPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/Nl2jsKF2tT/A4pgn5k9+P5mq
        zjKwrGE/g8MXYjq4fT8K9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC1mcnHQWDKPybVTzhsJXY+rnlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAF
        OZdGG9UAP3XUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wjj8BtjKfD9uhRkJl7YMPz7k
        zz8+htM+aaidcQ6aCz/xB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop0_site0_rg:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    3MYOShBT5T8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        AAAAAAAAAADD0LMVhRCCP1HNZzTGoNA/LA7oQcZb2r9LNctbN9C2vwAAAAAAAAAAAAAAAAAAAABh
        eTAa106pP0HxkSOCusS/HgsPqaIbuD97EMO8RuivPxuKN7siNbY/38I46NgJur+ySHQbCOvLP9+8
        WrnyC74/pyV96zFx0D8=
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        UqF8oE+/D0A=
    l1_ratio: 0
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l1
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0, loss: huber, penalty: l1}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        97lK2QdATUCmRu0gQKIHQGa1GBe7uWg/dQBR8vE/ZUC9VzF1uQIQQBkH6rUUvLg/jghm0yKNYz8h
        X11s8E25P1v3MUmgbsA/yNN3zKHQ0r9T7OOa1DPOv0VQCRM3udG/FeBi6CzZ0z91RPV459GSQNig
        nDotOeI/xMtzr2lMrD8=
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEBxPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4NMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/NV2jsKF2tT8GQikxiXFrQGiJ
        YVA4Lb4/IHEhkl9TmT8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [16]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC1mcnHQWDKPyfVTzhsJXY+rnlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3TUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wTj8BtjKfD8JAC1WKonnQBQO
        fH0JdYw/frw3jR4LRD8=
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop1_site0_r0:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    3ulPV3ok5D8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        6ELH1RNB7D9a1rBLX8Dxv46HlKokSOY/499HBdUs1D9z2KWDO+fgv5heXaWzLfO/AAAAAAAAAAAY
        ZQ+ID6j6v7Wv5x/yetc/hNkRFk9bkj/pADqgIMe2P2kDQ2pEy6E/7o6fjbiOUr/qF5kFgEz9v59M
        qlU4W8q/b5SKAumuAsC+ujGC4EPEPw==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        AORLTuz/QkA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0.5, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        97lK2QdATUCkRu0gQKIHQGe1GBe7uWg/dQBR8vE/ZUC9VzF1uQIQQBgH6rUUvLg/jghm0yKNYz8h
        X11s8E25P1v3MUmgbsA/x9N3zKHQ0r9S7OOa1DPOv0ZQCRM3udG/FeBi6CzZ0z/021LHi13BP69+
        ivC/24U/KYq4rM+uwT8M04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEByPtMAXw3dP8y34prq0jI/7Zob3pwLUkDeOHUI0krUP0XRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/Nl2jsKF2tT++4pgn5k9+P5mq
        zjKwrGE/hcMXYjq4fT8J9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC3mcnHQWDKPyfVTzhsJXY+r3lxYSlatECCaLj2ary5P1hc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3XUWY8tUz8/G11RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wjj8BtjKfD9rhRkJl7YMPz7k
        zz8+htM+bKidcQ6aCz/vB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop1_site0_sigma:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    beKG5nRx2j8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.001
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        6WgPX+WWfT83/fF1peeWPyKyybB4dYu/qTAz95Gker/Aj9r53i+EP/VSVb1CP5E/AAAAAAAAAAAD
        AbwzLkaJPwAAAAAAAAAAk1nIIVXwYT+Qsr0vMERgP56aYfN0imE/JER6GX5QYr+F8ILOZnOUP6Rl
        i7JzCzM/n7RWaQfrkz8AAAAAAAAAAA==
    epsilon: 0.01
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        iXxAuqt3pT8=
    l1_ratio: 0.15
    learning_rate: invscaling
    loss: huber
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: elasticnet
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.001, epsilon: 0.01, l1_ratio: 0.15, loss: huber, penalty: elasticnet}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        97lK2QdATUCkRu0gQKIHQGe1GBe7uWg/dQBR8vE/ZUC8VzF1uQIQQBkH6rUUvLg/jghm0yKNYz8h
        X11s8E25P1r3MUmgbsA/yNN3zKHQ0r9U7OOa1DPOv0ZQCRM3udG/F+Bi6CzZ0z/021LHi13BP69+
        ivC/24U/KYq4rM+uwT8M04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEByPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/NV2jsKF2tT+/4pgn5k9+P5mq
        zjKwrGE/hMMXYjq4fT8J9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC3mcnHQWDKPyfVTzhsJXY+rnlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3XUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wTj8BtjKfD9thRkJl7YMPz7k
        zz8+htM+a6idcQ6aCz/vB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop2_a:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    nZKLW9ewAEA=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        tF+yi4Kh3T/kQ/SOSkHgv+stNqAOjuE/Yf5AdhzOd79wPlNzBlvTv/4MgMlzouu/AAAAAAAAAAD+
        PvzMbk3ov8ps5zZr4Lo/yZa661/Cyz+n4JzQZinRP5niRP5oUM0/aZyUQPAyyr8qh5visx71v2La
        UhY+TNG/6IIM7bko+L+KnbUrFL29Pw==
    epsilon: 1
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        CSk7M03pXEA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 1, l1_ratio: 0.5, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        9blK2QdATUCkRu0gQKIHQGa1GBe7uWg/dABR8vE/ZUC8VzF1uQIQQBkH6rUUvLg/jghm0yKNYz8i
        X11s8E25P1v3MUmgbsA/yNN3zKHQ0r9U7OOa1DPOv0VQCRM3udG/FeBi6CzZ0z/021LHi13BP69+
        ivC/24U/KYq4rM+uwT8L04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1wB1SDI8KEByPtMAXw3dP8y34prq0jI/7Job3pwLUkDfOHUI0krUP0XRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+XcWIeXp6sP2q1+13VLrI/NV2jsKF2tT/A4pgn5k9+P5qq
        zjKwrGE/hMMXYjq4fT8K9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FzuOqbxaYkC3mcnHQWDKPyfVTzhsJXY+rnlxYSlatECEaLj2ary5P1hc2M4rNfw+AAAAAAAAAAAF
        OZdGG9UAP3XUWY8tUz8/Gl1RpEt+eD+JJa13NJhpP/gXcCnpqXQ/wTj8BtjKfD9uhRkJl7YMPz/k
        zz8+htM+a6idcQ6aCz/xB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
pop2_site0_r:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    VEMJrdvn9j8=
  model:
    C: 1.0
    _max_iter: 1000
    _tol: null
    alpha: 0.01
    average: false
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        4k/ukOC0uT8LRVO0RvHSv6DnjwYNnbA/p54do54alT+qJm6u5F2aP3P+QdSdsOG/AAAAAAAAAABS
        xVISkyqzvy3pnA5BEJ2/ggnVWj8DpT+mZGAiuzOsP+9Gb7metKY/+z5HhclLo7/Zvcn+XVrWv9gp
        LmPbT6O/WwceqEcf2b+V5ALOdSdQvw==
    epsilon: 0.01
    eta0: 0.01
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [1]
      - *id001
      - false
      - !!binary |
        Bgft3JmKQEA=
    l1_ratio: 0.5
    learning_rate: invscaling
    loss: squared_loss
    max_iter: 1000
    n_iter: null
    n_iter_: 1000
    penalty: l2
    power_t: 0.25
    random_state: null
    shuffle: true
    t_: 27001.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.01, epsilon: 0.01, l1_ratio: 0.5, loss: squared_loss, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        9blK2QdATUCkRu0gQKIHQGa1GBe7uWg/dABR8vE/ZUC8VzF1uQIQQBkH6rUUvLg/jghm0yKNYz8h
        X11s8E25P1v3MUmgbsA/yNN3zKHQ0r9U7OOa1DPOv0ZQCRM3udG/GOBi6CzZ0z/021LHi13BP69+
        ivC/24U/KYq4rM+uwT8O04nb+VOGPw==
    n_samples_seen_: 27
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        1gB1SDI8KEBxPtMAXw3dP8y34prq0jI/7Job3pwLUkDeOHUI0krUP0TRCPCOPnU/AAAAAAAA8D+c
        v6WvZTV3P4RMtPQwY5Y/tOXlRdrLsz+WcWIeXp6sP2q1+13VLrI/NV2jsKF2tT+/4pgn5k9+P5mq
        zjKwrGE/hMMXYjq4fT8K9qItBXBfPw==
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [17]
      - *id001
      - false
      - !!binary |
        FjuOqbxaYkC1mcnHQWDKPyfVTzhsJXY+rXlxYSlatECCaLj2ary5P1dc2M4rNfw+AAAAAAAAAAAG
        OZdGG9UAP3XUWY8tUz8/G11RpEt+eD+IJa13NJhpP/gXcCnpqXQ/wTj8BtjKfD9thRkJl7YMPz7k
        zz8+htM+a6idcQ6aCz/xB6wskuLOPg==
    with_mean: true
    with_std: true
  system_class: pop0_diffuse__site0_guinier_porod__pop1_diffuse__site0_spherical_normal__pop2_fcc__site0_spherical
