accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  AAAAAAAA8H8=
model:
  C: 1.0
  _max_iter: 1000
  _tol: null
  alpha: 0.0001
  average: false
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      BiWhow6HD7/izrVGg1vSPit7YaTMjvW+W0TVSCx8Ar9v1hD4sq0CP2s4oq+AIAc/WJoA/v///7/v
      IQRbUNXlvrMgISYcOtg+EtJCPtDvCb+KDHc2X2UmP4mKf+IDfc++YkCyNVihHT86hmUxu5TFvtJv
      +ALPH8I+OVhLUNWwxD4uShAejAHUPg==
  epsilon: 1
  eta0: 0.01
  fit_intercept: true
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1]
    - *id001
    - false
    - !!binary |
      WJoA/v///z8=
  l1_ratio: 0
  learning_rate: invscaling
  loss: huber
  max_iter: 1000
  n_iter: null
  n_iter_: 1000
  penalty: none
  power_t: 0.25
  random_state: null
  shuffle: true
  t_: 99001.0
  tol: null
  verbose: 0
  warm_start: false
parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
scaler:
  copy: true
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      hd5k+bTTD0DDy+JWYEzyP+erex9OX4Y/tX40Rs1qLED+2hJNkbwLQHF8uMlVHsE/jwhm0yKNYz+g
      hHibvIDNPylcWN4kM8Y/PwfZQP/e7L9YyqoQuorrv51yvCI0m+y/OexC+CkD7T8/l1kM2TPyP8Ym
      ecQAgwFA73qMud5myD/yxbI2HQz1Pw==
  n_samples_seen_: 112
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      aEtc6DLp4D8Bll7fXjqsP7hcc07UVnk//G54g3I9G0AtOZVjBKrtPwsp7lQUwYQ/AAAAAAAAIDy2
      TKnLDvuTPz7S7wp4idE/kaEBTX8juD8QN+NNXNiyP9YlfkImT7Y/jxF9XJPUuT/LTKrAXk0gQAm7
      oyN1HjFAFirSlLC9A0CrFwiOxLIaQA==
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      VBAKrKzf0T/Fg+h/kOZoPyp9OlWXEAQ/RkEKPCcwR0A9IyFDr3/rP1Au7s7M6xo/AAAAAAAAUDiA
      pPWDpvM4P8iNfTK8OLM/4VH1U2Y1gj/js4ptPTJ2P64CB8EwG38/YH+zY6rZhD+aIYSjM5xQQPos
      W+byUHJAjtjLRExbGEDXjjAWZkZGQA==
  with_mean: true
  with_std: true
