accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  AAAAAAAA8H8=
model:
  C: 1.0
  _max_iter: 1000
  _tol: null
  alpha: 0.0001
  average: false
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      SUZQ0yNlN79UtUK42GpGv07OPmYq0Ss/t9Ztds9y8r4zs4MawsE3P9anNTrwYRq/AAAAAAAAAAA/
      pBdMVdknP18On0yUYy6/Byx3MIixKr8f4MchxIQqvxXCg72iqiq/eVn7cljEKj/bPBEUkSIxv9nL
      e5Y2PzW/00ElLBdLIz8VSyy8N243vw==
  epsilon: 1
  eta0: 0.01
  fit_intercept: true
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1]
    - *id001
    - false
    - !!binary |
      qmLvtPD/D0A=
  l1_ratio: 0
  learning_rate: invscaling
  loss: huber
  max_iter: 1000
  n_iter: null
  n_iter_: 1000
  penalty: none
  power_t: 0.25
  random_state: null
  shuffle: true
  t_: 10001.0
  tol: null
  verbose: 0
  warm_start: false
parameters: {alpha: 0.0001, epsilon: 1, l1_ratio: 0, loss: huber, penalty: none}
scaler:
  copy: true
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      Pw35R39PIkDhzvRPyHfwP6TpYUw94Wk/I7U+LJgpGkBo0uTg4rcGQI3fonwP67o/jwhm0yKNYz+f
      ChMWY0G6P/DRgazGB7Y/Jrmn+lFg5b+x1iI09ubgvyPq/DxOEuS/CBOAwJWn5j8vGOJsXafJP3hh
      qtKgdKQ/epSxgCGgyz+8VcWjt46gPw==
  n_samples_seen_: 11
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      ceoFBeQEBUDS6CUyMLOdP9jvus3aCWw/bz7t1NjJD0Adpj9/yRvSP/T3q3pwMnQ/AAAAAAAAIDzD
      uHARdSikP1HI/gcmeKs/gZUyWvhTuj/9tozHB+W8P5O4InjaN7s/4SlAblgluT9L5eTjv5mcPxk0
      XAszqac/eMprIcuKpj/x1UHCcBegPw==
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      h5njC9icG0DaVF6+spBLPx/18vBBkeg+Y807Tg2UL0ClPUagtX60P8NXwzS4fvk+AAAAAAAAUDin
      kEn4imVZP+Yb50qDlGc/Z5Bt6k+phT9gMpDUNBeKP24ViyeiJoc/rZW3wYXCgz/nfEKG8o9JPwT1
      zQO4fmE/hND7lWLCXz/60czbAy9QPw==
  with_mean: true
  with_std: true
