accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  zUOT67uc2D8=
model:
  C: 1.0
  _max_iter: 1000
  _tol: null
  alpha: 0.01
  average: false
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      cBOLhTDE9D9ZPlfeolPwv2msxdEb3OM/GMU7DZCZxj8QCR6jg0LNv6xdDg95GOC/AAAAAAAAAAAf
      VvQ8QxsAwFiNGYSaoNA/CySsjQtXqL/81F52ARB9PzF8ovxcsKG/nPW3MD3trj/pFe1CwIX/v4WX
      3vT1ktW/Q7YopL+AAsDjBlgtCa/CPw==
  epsilon: 0.1
  eta0: 0.01
  fit_intercept: true
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1]
    - *id001
    - false
    - !!binary |
      bgcI/JNUQ0A=
  l1_ratio: 0
  learning_rate: invscaling
  loss: squared_loss
  max_iter: 1000
  n_iter: null
  n_iter_: 1000
  penalty: l2
  power_t: 0.25
  random_state: null
  shuffle: true
  t_: 41001.0
  tol: null
  verbose: 0
  warm_start: false
parameters: {alpha: 0.01, epsilon: 0.1, l1_ratio: 0, loss: squared_loss, penalty: l2}
scaler:
  copy: true
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      BqCPFQXlTUCjD37UW74HQL+3mOcQ0mg/MwRvNZZ7ZUAPI4vh0iIQQJs5pWySjbg/jghm0yKNYz/R
      LtY1W2q5P5HqY/wbksA/4A5epgxA0r8Uk/vkVV/Nv19nIW3iM9G/Ikws3RI90z9Z499qMDvBP+E3
      GqJ5pIQ/oDIwqjGZwT8DATEECpSGPw==
  n_samples_seen_: 41
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      +EImew0TJEAajldklfLYP8ctU/ForS4/e7Q59bKZUEB9mfz0JADRP7B/Mh2gtHI/AAAAAAAA8D+Z
      dU5CkSNzPw66toRAb5M/FQ+EWbdlsD9tqtdDT7unPxKsVR87Ia4/ASg+jQPGsT9NvDpCPlx6P3eN
      VZoYwWI/eKvIRNNveT+b7cCQ0cVePw==
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [17]
    - *id001
    - false
    - !!binary |
      Hn7vY7gvWUAXccoMD3PDP+1whXzQaG0+hPfWYCo5sUBBI+6IThCyP63XhFpf3vU+AAAAAAAAAABv
      MSMOyOT2PjqLZ8s+mzc/C1MHVvXNcD8dRbNYiplhPwB/Hl1xXmw/NqEMJFq+cz/lZBUS77YFPxKj
      8byR+9U+vI+Z4kA4BD9XcgzRr5fNPg==
  with_mean: true
  with_std: true
