system_class:
  accuracy: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    JvbjXXBm6T8=
  model:
    C: 1.0
    _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - &id002 !!python/name:numpy.ndarray ''
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10]
      - *id001
      - false
      - !!binary |
        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A
        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8=
    _max_iter: 10
    _tol: null
    alpha: 0.0001
    average: false
    class_weight: null
    classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10]
      - !!python/object/apply:numpy.dtype
        args: [U119, 0, 1]
        state: !!python/tuple [3, <, null, null, null, 476, 4, 8]
      - false
      - !!binary |
        TgAAAG8AAABpAAAAcwAAAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYAAAB1
        AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAGcAAAB1AAAAaQAAAG4A
        AABpAAAAZQAAAHIAAABfAAAAcAAAAG8AAAByAAAAbwAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAAAABf
        AAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAA
        AABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8AAABwAAAAbwAAAHIAAABvAAAAZAAA
        AF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAA
        XwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABj
        AAAAYQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAA
        AAAyAAAAXwAAAGYAAABjAAAAYwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAA
        AHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAAAF8A
        AABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAAYQAA
        AGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAAAGYA
        AAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAA
        AGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABfAAAA
        XwAAAHAAAABvAAAAcAAAADEAAABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABf
        AAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAAAF8A
        AABwAAAAbwAAAHIAAABvAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABvAAAAcAAAADAA
        AABfAAAAZAAAAGkAAABmAAAAZgAAAHUAAABzAAAAZQAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAA
        ADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAA
        cgAAAG0AAABhAAAAbAAAAF8AAABfAAAAcAAAAG8AAABwAAAAMQAAAF8AAABmAAAAYwAAAGMAAABf
        AAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAAaAAAAGUAAAByAAAAaQAAAGMA
        AABhAAAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAABkAAAAaQAAAGYAAABmAAAAdQAAAHMAAABlAAAAXwAA
        AF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGkAAABjAAAA
        YQAAAGwAAABfAAAAbgAAAG8AAAByAAAAbQAAAGEAAABsAAAAXwAAAF8AAABwAAAAbwAAAHAAAAAx
        AAAAXwAAAGgAAABhAAAAcgAAAGQAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABlAAAAcwAAAF8A
        AABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAZwAAAHUAAABpAAAAbgAAAGkAAABlAAAAcgAA
        AF8AAABwAAAAbwAAAHIAAABvAAAAZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAbwAAAHAAAAAwAAAAXwAAAGQAAABpAAAAZgAA
        AGYAAAB1AAAAcwAAAGUAAABfAAAAXwAAAHMAAABpAAAAdAAAAGUAAAAwAAAAXwAAAHMAAABwAAAA
        aAAAAGUAAAByAAAAaQAAAGMAAABhAAAAbAAAAF8AAABuAAAAbwAAAHIAAABtAAAAYQAAAGwAAABf
        AAAAXwAAAHAAAABvAAAAcAAAADEAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgA
        AABlAAAAcgAAAGUAAABzAAAAXwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAA
        AGkAAABuAAAAaQAAAGUAAAByAAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAXwAAAF8AAABwAAAA
        bwAAAHAAAAAyAAAAXwAAAGgAAABhAAAAcgAAAGQAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIAAABl
        AAAAcwAAAF8AAABfAAAAcwAAAGkAAAB0AAAAZQAAADAAAABfAAAAcwAAAHAAAABoAAAAZQAAAHIA
        AABpAAAAYwAAAGEAAABsAAAAXwAAAG4AAABvAAAAcgAAAG0AAABhAAAAbAAAAHAAAABvAAAAcAAA
        ADAAAABfAAAAaAAAAGEAAAByAAAAZAAAAF8AAABzAAAAcAAAAGgAAABlAAAAcgAAAGUAAABzAAAA
        XwAAAF8AAABzAAAAaQAAAHQAAABlAAAAMAAAAF8AAABnAAAAdQAAAGkAAABuAAAAaQAAAGUAAABy
        AAAAXwAAAHAAAABvAAAAcgAAAG8AAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAcAAAAG8AAABwAAAAMAAAAF8AAAB1AAAAbgAAAGkAAABkAAAAZQAAAG4AAAB0AAAA
        aQAAAGYAAABpAAAAZQAAAGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10, 13]
      - *id001
      - false
      - !!binary |
        ShO1rj97MMB2MOHFGvETQIIFvSL+syFAozOFfxAKAkAUcIxwJByTP1Tnu9v1vjnASS7SN6K947/c
        7PXesQ3bP/g57tn9CQDAfmEykhO0JUB+J60bdN0uwHP2oUYuIw1AQ0bgH+jfMcAs9qSUfsUHwBOs
        MAjhZTLAJ5atAQm3J0De81Kc6pz7P225MSAEjzBAAEZ93SJvN0BTNPXERkIjQH6CMOK8BidA6t3k
        ICInrD+Xb8JI7xcuwPP7Ia54iTHAa97i4QOxL8Dn9vGuyagsQOurpDAQCDRAjeIyb3/ZCkCOpETj
        lhcjwOQdQFE8KytA9WMGsA0/GsBEK3qVzjwbQNZu8f66/yVA6nTnTYCML8A223wpuhXdPy66RKSi
        zBrAaE7BwIDcFcCVhL4h+HEZwLIbNJJJ4xtAjzJyr37XD0CR/UZHUEw9wBhd70wzXzLAcQO7+EQD
        KMDmzR+tkwbAPzSgZ2H2ayJALoW2jkhPJMCFaHF0X2o5wJGqphpMJv0/6YvDGuXe6b9WbfR4vBgG
        QKZY1MCgLsI/Njd+peDX/D8jUEw3BhErwNYEJ4nKqz3AsKKbM+yJF8B1Cr+HypgbwKbYKpTK9B7A
        pyVCJxJP8D9kDwjAZHkRQNuANetJRzvAuuT5tl5Twb9vDDygDloqwNWjVFW4ixvAQGCFehbpJsC8
        874F6IYtQC/hNENCyiZAzXGC9UpgFUDcTdqNKZwuwCNq5FrLy/U/jxyWyjjKzj86VBcWOOAkwJfk
        e7qHokLAys9lcCokJsBR9f5+n+Dov7ldmmz4DSnAgvlgqo8PHcAfFCvlARQmwP6xBrH1lStA4LJF
        Dq9UMcAVb+XsL/4UwLyo6tkwkQTAD2M0CL6+IMBm2nEeeN45wNj0xfb78dW/ssZS0fm9GkDyQXMc
        rhUswHmY8ZJx26I/sJ1XXVlhJ8B5ZscHeXUrQGCvUSI06BLAe22dzul7MkAtW6HZCHQvwHgU54Cm
        ECvALtB0AnZWH8DGL7857TUkwD7RwldyOBDAHMoiRk00QsBFtyU3QWkfQKBitwwKhNu/Kb+2Waoa
        IECIVVEFAV8hwGdPoUeL/xfAlcBNxFfKH8AvgkDOIKEiQIoYYYFLtijA81MoWQsfIsCq8FIt1iYV
        QAp9N2PRpum/LZ58ygCsJEBR+Jren9E7QAiJipOD8THAJX1huGkBO0DZdpkywh0EQO5pWeHQMQ/A
        OnupMr6wJsBL88GjpvoYwMBYRFBM9QBAkJUFdg+iGMDz/T76+kcYwBOYrpRL5xDAMcv/8uwL679p
        Dnqx/NX1v0MK+2WbQPC/Pr3M7DHOA0CIBmO6iFsHQN1Be7djp+G/NWbCxMzbJsCd9/+PDv4twEyB
        UHiZzyjA7lSjYDqwJEA=
    epsilon: 0.1
    eta0: 0.0
    fit_intercept: true
    intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [10]
      - *id001
      - false
      - !!binary |
        YwvldYTL7j8Jh6YJCOljwIaRWP8wkVLAftDJEH2aTMB77sy02sxXwJ4Q2IA+RFDAyH8fVcD2TcAC
        KdX1buVTwMDJRQy3ZWDAMRUf1UAzXMA=
    l1_ratio: 0.5
    learning_rate: optimal
    loss: log
    loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
    max_iter: 10
    n_iter: null
    n_iter_: 10
    n_jobs: 1
    penalty: l2
    power_t: 0.5
    random_state: null
    shuffle: true
    t_: 6781.0
    tol: null
    verbose: 0
    warm_start: false
  parameters: {alpha: 0.0001, l1_ratio: 0.5, penalty: l2}
  scaler:
    copy: true
    mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        kRMEPsEsNEClcdeNtcf2P5hSDQwQU3k/tiWORAbZNED1yV2YyyYJQBMtmnQAM7o/lprxcGOeXj/Z
        uO+3jjnBPysBytnYZsK/0+L5Nud31b97FhZQM2jRvwrfbkEFUdS/SjNYpomg1j8=
    n_samples_seen_: 938
    scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        nwsVsEDzLkAsaEmx5LblP1zlQyCu04Q/Q8+D3VDvREBsi2ym/M/wPybSDwYWKaA/wyKq7KG0Mj8S
        l2woQkG6P+H4/mjBpA9AODlgGX+W2D/Elw+38B/UP5TiC11JMtc/5BOIwy/92T8=
    var_: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - *id002
      - !!python/tuple [0]
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple [13]
      - *id001
      - false
      - !!binary |
        h3kcaVLvbUDOu+bwQnjdPy66o9gjHBs/Gfs7q0Vkm0CO0MD1iKrxPw8GHY2VUlA/0XoylmPedT6W
        df2WkIqFP4gzc/6GSi9AbA2Xb4Lkwj/Y05GMGVC5P20MrHuY0MA/2cEP3W0bxT8=
    with_mean: true
    with_std: true
