accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  4M6GaaWi7z8=
model:
  C: 1.0
  _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [2]
    - *id001
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAADwPw==
  _max_iter: 5
  _tol: null
  alpha: 0.1
  average: false
  class_weight: null
  classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [2]
    - !!python/object/apply:numpy.dtype
      args: [U1, 0, 1]
      state: !!python/tuple [3, <, null, null, null, 4, 4, 8]
    - false
    - !!binary |
      MAAAADEAAAA=
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1, 13]
    - *id001
    - false
    - !!binary |
      luIj0Dt8wj9g1Rq46tqPvwp+1GJrf9G/aYh9CsL7pj+WPsVXxUqjPwj3gaJO786/BCTlqNEAnD9u
      ZNcsbp7NvxqeGEnZfYC/dTW17osr078penNQ6x7UvzAqNGtzldO/rf5sf+i30j8=
  epsilon: 0.1
  eta0: 0.0
  fit_intercept: true
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1]
    - *id001
    - false
    - !!binary |
      iWVSEkFwCkA=
  l1_ratio: 0.15
  learning_rate: optimal
  loss: log
  loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
  max_iter: null
  n_iter: null
  n_iter_: 5
  n_jobs: 1
  penalty: l2
  power_t: 0.5
  random_state: null
  shuffle: true
  t_: 8971.0
  tol: null
  verbose: 0
  warm_start: false
parameters: {alpha: 0.1, l1_ratio: 0.15, penalty: l2}
scaler:
  copy: true
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      7oLQX3HHNUBLtBfWrj74P58NFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOp8mmKfR7s/8MRKQRZ0YD/F
      QTehTlXCP8yJNwnPBNi/R91tOw8U2783w1LtxznXv5vlA+htBNq/X7r9Vd8Z3D8=
  n_samples_seen_: 1946
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      y3Hbe9lRNUCksMwX+JjnP87cpyh9foM/lF7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
      SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7oGnZvSxNU/SjlhTjSF1z8=
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      80uymn1ofEBwx5vev2bhP+QLojdRwBc/2EgM2trtkEAU5ykWEuv1P3VsGnMEHE4/dtAE1BBAlj6p
      y0nS1XGDP9RELnJACFZAhH8MPCgAwD83AztpvQK5P5DzNAsenr0/AsrMq6VJwT8=
  with_mean: true
  with_std: true
