!!python/object/apply:collections.OrderedDict
- - - version
    - [0, 19, 1]
  - - scalers
    - diffraction_peaks:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id001 !!python/name:numpy.ndarray ''
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - &id002 !!python/object/apply:numpy.dtype
            args: [f8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2cTtOTsIHY/2r3ZibowNEBcw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L9z8KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            pr9zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCq8cRsQCDvP6xaIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mEHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCj0hhUnUbuP06GvElAAEg/PMxDKOwtlz4p
            ucqsJVF7PzeWk9fZ/FdAH0Z44biYpz+cP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      guinier_porod:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2cTtOTsIHY/2r3ZibowNEBcw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L9z8KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            pr9zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCq8cRsQCDvP6xaIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mEHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCj0hhUnUbuP06GvElAAEg/PMxDKOwtlz4p
            ucqsJVF7PzeWk9fZ/FdAH0Z44biYpz+cP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      spherical_normal:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            6hz5jxCaN0Ck39Lgt1n4P2cTtOTsIHY/2r3ZibowNEBcw+UbX5QKQHKjN9g6Rbo/BiBsuBmWYD/n
            vjWivBjAP9J1QpTGz9y/cRNToiIj4L9z8KVSQnbbv7fiFMYi796/NHhWO+bH4D8=
        n_samples_seen_: 1784
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            pr9zixVZNUDrOQTLfnDnP/pkf1tapH0/bRwSV14VQUCq8cRsQCDvP6xaIAagtps/PbfTlwtCQz89
            7hSkAOi0P6RAauxElyNAjGoNlZl6yz878ZbzGRTLPxxT1LktE8s/2xwijiIfzD8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            mEHcjch7fEChlFm9QSvhP4Pk/+QvdQs/4UzXAoU9kkCj0hhUnUbuP06GvElAAEg/PMxDKOwtlz4p
            ucqsJVF7PzeWk9fZ/FdAH0Z44biYpz+cP5Rr+OmmPz9PJKho6KY/F2XUw5q2qD8=
        with_mean: true
        with_std: true
      unidentified:
        copy: true
        mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            7YLQX3HHNUBLtBfWrj74P58NFRPCKXw/EUYq2Do/M0BZOyNt+nQKQOl8mmKfR7s/8MRKQRZ0YD/F
            QTehTlXCP8+JNwnPBNi/R91tOw8U2783w1LtxznXv5vlA+htBNq/X7r9Vd8Z3D8=
        n_samples_seen_: 1946
        scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            ynHbe9lRNUCjsMwX+JjnP87cpyh9foM/lF7Y0T91QEBIb7yZDbryPx/HZyhTCp8/WNb56DneQj+d
            SwN+zPG4Pykt7sSAxiJAsVip2bqg1j8qhM6IGAHUP7kGnZvSxNU/SjlhTjSF1z8=
        var_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [13]
          - *id002
          - false
          - !!binary |
            8kuymn1ofEBvx5vev2bhP+QLojdRwBc/2EgM2trtkEAU5ykWEuv1P3ZsGnMEHE4/dtAE1BBAlj6p
            y0nS1XGDP9RELnJACFZAhH8MPCgAwD83AztpvQK5P4/zNAsenr0/AsrMq6VJwT8=
        with_mean: true
        with_std: true
  - - models
    - diffraction_peaks:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 1.0e-05
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - &id003 !!python/object/apply:numpy.dtype
            args: [i8, 0, 1]
            state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            /Xim1KiPb0CcXIYKlNFRQM/x94ahjkfAOWzO8jBxbUAywT13NnhOwN/nT310s3HA/9SJqhiJREAZ
            9sBaVjZYwAkIGFs9UjtAzsnU5AMxJsDgcQkh5L5LQJcxMaGmDSVAj4I5UE1HP0A=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            3eh14PHMW0A=
        l1_ratio: 0.15
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: none
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      guinier_porod:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.1
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAp
            6+l9JMLyPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            93fde5XV3b8=
        l1_ratio: 0
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: l1
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      spherical_normal:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.01
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMJLr38yLDv1+7+XYfo+u/AAAAAAAAAADg
            cFpySMcFwAAAAAAAAAAAAAAAAAAAAABl/kIVjpboPwAAAAAAAAAAAAAAAAAAAAA=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            OSws98NQDUA=
        l1_ratio: 0.85
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 8921.0
        tol: null
        verbose: 0
        warm_start: false
      unidentified:
        C: 1.0
        _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id002
          - false
          - !!binary |
            AAAAAAAA8D8AAAAAAADwPw==
        _max_iter: 5
        _tol: null
        alpha: 0.01
        average: false
        class_weight: null
        classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [2]
          - *id003
          - false
          - !!binary |
            AAAAAAAAAAABAAAAAAAAAA==
        coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1, 13]
          - *id002
          - false
          - !!binary |
            tyyh1SZlub8AAAAAAAAAAHIzJbtYKuQ/AAAAAAAAAAAAAAAAAAAAAKni604AJuI/AAAAAAAAAAC3
            UX+hfpLEPwAAAAAAAAAACwRBfyuJ3D/wZQrutIrnPwSZXkO/ZeE/3XaRmCSG1r8=
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - *id001
          - !!python/tuple [0]
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple [1]
          - *id002
          - false
          - !!binary |
            l4q53SUbFMA=
        l1_ratio: 0.5
        learning_rate: optimal
        loss: log
        loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
        max_iter: null
        n_iter: null
        n_iter_: 5
        n_jobs: 1
        penalty: elasticnet
        power_t: 0.5
        random_state: null
        shuffle: true
        t_: 9731.0
        tol: null
        verbose: 0
        warm_start: false
  - - accuracy
    - diffraction_peaks: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        z5EYrDDs7j8=
      guinier_porod: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        +tcHAepo6j8=
      spherical_normal: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        yySCUAm57z8=
      unidentified: !!python/object/apply:numpy.core.multiarray.scalar
      - *id002
      - !!binary |
        0Vm26ByO7z8=
