accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  gNhrO4147j8=
model:
  C: 1.0
  _expanded_class_weight: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - &id002 !!python/name:numpy.ndarray ''
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [2]
    - *id001
    - false
    - !!binary |
      AAAAAAAA8D8AAAAAAADwPw==
  _max_iter: 5
  _tol: null
  alpha: 0.1
  average: false
  class_weight: null
  classes_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [2]
    - !!python/object/apply:numpy.dtype
      args: [U1, 0, 1]
      state: !!python/tuple [3, <, null, null, null, 4, 4, 8]
    - false
    - !!binary |
      MAAAADEAAAA=
  coef_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1, 13]
    - *id001
    - false
    - !!binary |
      4uDYjlNE4j8AAAAAAAAAALQKzx9Da8u/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1
      uZYWudHwvwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
  epsilon: 0.1
  eta0: 0.0
  fit_intercept: true
  intercept_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [1]
    - *id001
    - false
    - !!binary |
      db6b/fHj9z8=
  l1_ratio: 0
  learning_rate: optimal
  loss: log
  loss_function_: !!python/object/apply:sklearn.linear_model.sgd_fast.Log []
  max_iter: null
  n_iter: null
  n_iter_: 5
  n_jobs: 1
  penalty: l1
  power_t: 0.5
  random_state: null
  shuffle: true
  t_: 2051.0
  tol: null
  verbose: 0
  warm_start: false
parameters: {alpha: 0.1, l1_ratio: 0, penalty: l1}
scaler:
  copy: true
  mean_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      gbKkbLcGJ0Ak9JSxRIvxP+MamGk7GoE/qo1MolL5IED9een0ty4LQJtJmxHoar4/n2Ie0hKWXj8g
      2T7d56vDP3HNT24Ynee/ngNK/2mq4L/cgeqzdmTevx80qTsOTeC/CM9BHWX+4D8=
  n_samples_seen_: 482
  scale_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      V20jZOAsIEBMv2EaGBW7P8XPXHN8qIM//vPQehp9G0ARTUHQjkT3Py/b2tXrqZQ/S7FwEQMgIz+g
      2JFou6i7P6pfWbueeSlAP/PoRMukzD8IqMS4sRfMP/yQDSU0scs/PgD5Jgktzj8=
  var_: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id002
    - !!python/tuple [0]
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple [13]
    - *id001
    - false
    - !!binary |
      25O4pj5aUEDDujmUpuuGP90JO8sVJxg/mgU2xgWdR0DfUdAsIOsAQHL4PCrarzo/df6xVUfcVj5u
      qIn0NeiHP7jXN0DWR2RATDAlYbSjqT/qyKyOiKmoP1TDtUfd9qc/4BrTirB0rD8=
  with_mean: true
  with_std: true
